syntax = "proto3";

package kirby.admin.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "kirby/common/v1/entity.proto";
import "validate/validate.proto";

option go_package = "github.com/yvvlee/kirby/server/gen/kirby/admin/v1;adminv1";

service AuthService {
  rpc Login(LoginRequest) returns (LoginReply) {
    option (google.api.http) = {post: "/auth/login", body: "*"};
  }
  rpc Refresh(google.protobuf.Empty) returns (LoginReply) {
    option (google.api.http) = {post: "/auth/refresh", body: "*"};
  }
  rpc Logout(google.protobuf.Empty) returns (google.protobuf.Empty) {
    option (google.api.http) = {post: "/auth/logout", body: "*"};
  }
  rpc Me(google.protobuf.Empty) returns (MeReply) {
    option (google.api.http) = {get: "/auth/me"};
  }
}

message LoginRequest {
  string username = 1 [(validate.rules).string = {min_len: 1, max_len: 128}];
  string password = 2 [(validate.rules).string = {min_len: 1, max_len: 1024}];
}

message LoginReply {
  string access_token = 1;
  uint32 expires_in = 2;
  kirby.common.v1.User user = 3;
}

message MeReply {
  kirby.common.v1.User user = 1;
  repeated kirby.common.v1.Environment environments = 2;
}
