syntax = "proto3";

package kirby.admin.v1;

import "google/api/annotations.proto";
import "kirby/admin/v1/snapshot.proto";
import "validate/validate.proto";

option go_package = "github.com/yvvlee/kirby/server/gen/kirby/admin/v1;adminv1";

service PublicationService {
  rpc PublishSnapshot(PublishSnapshotRequest) returns (SnapshotReply) {
    option (google.api.http) = {
      post: "/admin/environments/{environment_id}/snapshots/{snapshot_id}/publish"
      body: "*"
    };
  }
  rpc UnpublishSnapshot(PublishSnapshotRequest) returns (SnapshotReply) {
    option (google.api.http) = {
      post: "/admin/environments/{environment_id}/snapshots/{snapshot_id}/unpublish"
      body: "*"
    };
  }
}

message PublishSnapshotRequest {
  int64 environment_id = 1 [(validate.rules).int64 = {gt: 0}];
  int64 snapshot_id = 2 [(validate.rules).int64 = {gt: 0}];
  uint32 version = 3;
}
