syntax = "proto3";

package kirby.admin.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "kirby/common/v1/entity.proto";
import "validate/validate.proto";

option go_package = "github.com/yvvlee/kirby/server/gen/kirby/admin/v1;adminv1";

service RoleService {
  rpc ListRoles(google.protobuf.Empty) returns (ListRolesReply) {
    option (google.api.http) = {get: "/admin/roles"};
  }
  rpc CreateRole(CreateRoleRequest) returns (RoleReply) {
    option (google.api.http) = {post: "/admin/roles", body: "*"};
  }
  rpc UpdateRole(UpdateRoleRequest) returns (RoleReply) {
    option (google.api.http) = {put: "/admin/roles/{role_id}", body: "*"};
  }
  rpc DeleteRole(RoleIDRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/admin/roles/{role_id}"};
  }
  rpc ListPermissions(google.protobuf.Empty) returns (ListPermissionsReply) {
    option (google.api.http) = {get: "/admin/permissions"};
  }
  rpc UpdateRolePermissions(UpdateRolePermissionsRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {put: "/admin/roles/{role_id}/permissions", body: "*"};
  }
}

message RoleIDRequest {
  int64 role_id = 1 [(validate.rules).int64 = {gt: 0}];
}

message CreateRoleRequest {
  string key = 1 [(validate.rules).string = {
    min_len: 1, max_len: 64, pattern: "^[a-z][a-z0-9_:.-]*$"
  }];
  string name = 2 [(validate.rules).string = {min_len: 1, max_len: 64}];
  string description = 3 [(validate.rules).string = {max_len: 255}];
}

message UpdateRoleRequest {
  int64 role_id = 1 [(validate.rules).int64 = {gt: 0}];
  string name = 2 [(validate.rules).string = {min_len: 1, max_len: 64}];
  string description = 3 [(validate.rules).string = {max_len: 255}];
  uint32 version = 55;
}

message UpdateRolePermissionsRequest {
  int64 role_id = 1 [(validate.rules).int64 = {gt: 0}];
  repeated int64 permission_ids = 2 [(validate.rules).repeated = {
    unique: true, items: {int64: {gt: 0}}
  }];
}

message RoleReply {
  kirby.common.v1.Role role = 1;
}

message ListRolesReply {
  repeated kirby.common.v1.Role list = 1;
}

message ListPermissionsReply {
  repeated kirby.common.v1.Permission list = 1;
}
