syntax = "proto3";

package kirby.admin.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "kirby/common/v1/entity.proto";
import "validate/validate.proto";

option go_package = "github.com/yvvlee/kirby/server/gen/kirby/admin/v1;adminv1";

service UserService {
  rpc ListUsers(google.protobuf.Empty) returns (ListUsersReply) {
    option (google.api.http) = {get: "/admin/users"};
  }
  rpc CreateUser(CreateUserRequest) returns (UserReply) {
    option (google.api.http) = {post: "/admin/users", body: "*"};
  }
  rpc UpdateUser(UpdateUserRequest) returns (UserReply) {
    option (google.api.http) = {put: "/admin/users/{user_id}", body: "*"};
  }
  rpc UpdateUserPassword(UpdateUserPasswordRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {put: "/admin/users/{user_id}/password", body: "*"};
  }
  rpc UpdateUserStatus(UpdateUserStatusRequest) returns (UserReply) {
    option (google.api.http) = {put: "/admin/users/{user_id}/status", body: "*"};
  }
}

message CreateUserRequest {
  string username = 1 [(validate.rules).string = {min_len: 1, max_len: 128}];
  string display_name = 2 [(validate.rules).string = {min_len: 1, max_len: 128}];
  string password = 3 [(validate.rules).string = {min_len: 12, max_len: 1024}];
  bool is_system_admin = 4;
}

message UpdateUserRequest {
  int64 user_id = 1 [(validate.rules).int64 = {gt: 0}];
  string display_name = 2 [(validate.rules).string = {min_len: 1, max_len: 128}];
  bool is_system_admin = 3;
  uint32 version = 55;
}

message UpdateUserPasswordRequest {
  int64 user_id = 1 [(validate.rules).int64 = {gt: 0}];
  string password = 2 [(validate.rules).string = {min_len: 12, max_len: 1024}];
}

message UpdateUserStatusRequest {
  int64 user_id = 1 [(validate.rules).int64 = {gt: 0}];
  bool enabled = 2;
  uint32 version = 55;
}

message UserReply {
  kirby.common.v1.User user = 1;
}

message ListUsersReply {
  repeated kirby.common.v1.User list = 1;
}
