// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/asset.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAssetServiceCompleteAsset = "/kirby.admin.v1.AssetService/CompleteAsset"
const OperationAssetServicePresignAsset = "/kirby.admin.v1.AssetService/PresignAsset"

type AssetServiceHTTPServer interface {
	CompleteAsset(context.Context, *CompleteAssetRequest) (*CompleteAssetReply, error)
	PresignAsset(context.Context, *PresignAssetRequest) (*PresignAssetReply, error)
}

func RegisterAssetServiceHTTPServer(s *http.Server, srv AssetServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/projects/{project_id}/assets/presign", _AssetService_PresignAsset0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/projects/{project_id}/assets/complete", _AssetService_CompleteAsset0_HTTP_Handler(srv))
}

func _AssetService_PresignAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PresignAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServicePresignAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PresignAsset(ctx, req.(*PresignAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PresignAssetReply)
		return ctx.Result(200, reply)
	}
}

func _AssetService_CompleteAsset0_HTTP_Handler(srv AssetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAssetServiceCompleteAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteAsset(ctx, req.(*CompleteAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteAssetReply)
		return ctx.Result(200, reply)
	}
}

type AssetServiceHTTPClient interface {
	CompleteAsset(ctx context.Context, req *CompleteAssetRequest, opts ...http.CallOption) (rsp *CompleteAssetReply, err error)
	PresignAsset(ctx context.Context, req *PresignAssetRequest, opts ...http.CallOption) (rsp *PresignAssetReply, err error)
}

type AssetServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAssetServiceHTTPClient(client *http.Client) AssetServiceHTTPClient {
	return &AssetServiceHTTPClientImpl{client}
}

func (c *AssetServiceHTTPClientImpl) CompleteAsset(ctx context.Context, in *CompleteAssetRequest, opts ...http.CallOption) (*CompleteAssetReply, error) {
	var out CompleteAssetReply
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/assets/complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServiceCompleteAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AssetServiceHTTPClientImpl) PresignAsset(ctx context.Context, in *PresignAssetRequest, opts ...http.CallOption) (*PresignAssetReply, error) {
	var out PresignAssetReply
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/assets/presign"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAssetServicePresignAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
