// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/asset.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignAssetRequest) Reset() {
	*x = PresignAssetRequest{}
	mi := &file_admin_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignAssetRequest) ProtoMessage() {}

func (x *PresignAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignAssetRequest.ProtoReflect.Descriptor instead.
func (*PresignAssetRequest) Descriptor() ([]byte, []int) {
	return file_admin_asset_proto_rawDescGZIP(), []int{0}
}

func (x *PresignAssetRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *PresignAssetRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PresignAssetRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PresignAssetRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PresignAssetRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PresignAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UploadMethod  string                 `protobuf:"bytes,5,opt,name=upload_method,json=uploadMethod,proto3" json:"upload_method,omitempty"`
	FormFields    map[string]string      `protobuf:"bytes,6,rep,name=form_fields,json=formFields,proto3" json:"form_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignAssetReply) Reset() {
	*x = PresignAssetReply{}
	mi := &file_admin_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignAssetReply) ProtoMessage() {}

func (x *PresignAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignAssetReply.ProtoReflect.Descriptor instead.
func (*PresignAssetReply) Descriptor() ([]byte, []int) {
	return file_admin_asset_proto_rawDescGZIP(), []int{1}
}

func (x *PresignAssetReply) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PresignAssetReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *PresignAssetReply) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PresignAssetReply) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PresignAssetReply) GetUploadMethod() string {
	if x != nil {
		return x.UploadMethod
	}
	return ""
}

func (x *PresignAssetReply) GetFormFields() map[string]string {
	if x != nil {
		return x.FormFields
	}
	return nil
}

type CompleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAssetRequest) Reset() {
	*x = CompleteAssetRequest{}
	mi := &file_admin_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAssetRequest) ProtoMessage() {}

func (x *CompleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAssetRequest.ProtoReflect.Descriptor instead.
func (*CompleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_admin_asset_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteAssetRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CompleteAssetRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CompleteAssetRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CompleteAssetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *common.Asset          `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAssetReply) Reset() {
	*x = CompleteAssetReply{}
	mi := &file_admin_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAssetReply) ProtoMessage() {}

func (x *CompleteAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAssetReply.ProtoReflect.Descriptor instead.
func (*CompleteAssetReply) Descriptor() ([]byte, []int) {
	return file_admin_asset_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteAssetReply) GetAsset() *common.Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_admin_asset_proto protoreflect.FileDescriptor

const file_admin_asset_proto_rawDesc = "" +
	"\n" +
	"\x11admin/asset.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/entity.proto\x1a\x17validate/validate.proto\"\xe1\x01\n" +
	"\x13PresignAssetRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tprojectId\x12&\n" +
	"\bfilename\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\bfilename\x12-\n" +
	"\fcontent_type\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\vcontentType\x12\x1b\n" +
	"\x04size\x18\x05 \x01(\x04B\a\xfaB\x042\x02 \x00R\x04size\"\xae\x03\n" +
	"\x11PresignAssetReply\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12H\n" +
	"\aheaders\x18\x03 \x03(\v2..kirby.admin.v1.PresignAssetReply.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12#\n" +
	"\rupload_method\x18\x05 \x01(\tR\fuploadMethod\x12R\n" +
	"\vform_fields\x18\x06 \x03(\v21.kirby.admin.v1.PresignAssetReply.FormFieldsEntryR\n" +
	"formFields\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fFormFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x14CompleteAssetRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12&\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tprojectId\x12)\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\bR\tobjectKey\"B\n" +
	"\x12CompleteAssetReply\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.kirby.common.v1.AssetR\x05asset2\xf0\x02\n" +
	"\fAssetService\x12\xac\x01\n" +
	"\fPresignAsset\x12#.kirby.admin.v1.PresignAssetRequest\x1a!.kirby.admin.v1.PresignAssetReply\"T\x82\xd3\xe4\x93\x02N:\x01*\"I/admin/environments/{environment_id}/projects/{project_id}/assets/presign\x12\xb0\x01\n" +
	"\rCompleteAsset\x12$.kirby.admin.v1.CompleteAssetRequest\x1a\".kirby.admin.v1.CompleteAssetReply\"U\x82\xd3\xe4\x93\x02O:\x01*\"J/admin/environments/{environment_id}/projects/{project_id}/assets/completeB2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_asset_proto_rawDescOnce sync.Once
	file_admin_asset_proto_rawDescData []byte
)

func file_admin_asset_proto_rawDescGZIP() []byte {
	file_admin_asset_proto_rawDescOnce.Do(func() {
		file_admin_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_asset_proto_rawDesc), len(file_admin_asset_proto_rawDesc)))
	})
	return file_admin_asset_proto_rawDescData
}

var file_admin_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_asset_proto_goTypes = []any{
	(*PresignAssetRequest)(nil),  // 0: kirby.admin.v1.PresignAssetRequest
	(*PresignAssetReply)(nil),    // 1: kirby.admin.v1.PresignAssetReply
	(*CompleteAssetRequest)(nil), // 2: kirby.admin.v1.CompleteAssetRequest
	(*CompleteAssetReply)(nil),   // 3: kirby.admin.v1.CompleteAssetReply
	nil,                          // 4: kirby.admin.v1.PresignAssetReply.HeadersEntry
	nil,                          // 5: kirby.admin.v1.PresignAssetReply.FormFieldsEntry
	(*common.Asset)(nil),         // 6: kirby.common.v1.Asset
}
var file_admin_asset_proto_depIdxs = []int32{
	4, // 0: kirby.admin.v1.PresignAssetReply.headers:type_name -> kirby.admin.v1.PresignAssetReply.HeadersEntry
	5, // 1: kirby.admin.v1.PresignAssetReply.form_fields:type_name -> kirby.admin.v1.PresignAssetReply.FormFieldsEntry
	6, // 2: kirby.admin.v1.CompleteAssetReply.asset:type_name -> kirby.common.v1.Asset
	0, // 3: kirby.admin.v1.AssetService.PresignAsset:input_type -> kirby.admin.v1.PresignAssetRequest
	2, // 4: kirby.admin.v1.AssetService.CompleteAsset:input_type -> kirby.admin.v1.CompleteAssetRequest
	1, // 5: kirby.admin.v1.AssetService.PresignAsset:output_type -> kirby.admin.v1.PresignAssetReply
	3, // 6: kirby.admin.v1.AssetService.CompleteAsset:output_type -> kirby.admin.v1.CompleteAssetReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_asset_proto_init() }
func file_admin_asset_proto_init() {
	if File_admin_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_asset_proto_rawDesc), len(file_admin_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_asset_proto_goTypes,
		DependencyIndexes: file_admin_asset_proto_depIdxs,
		MessageInfos:      file_admin_asset_proto_msgTypes,
	}.Build()
	File_admin_asset_proto = out.File
	file_admin_asset_proto_goTypes = nil
	file_admin_asset_proto_depIdxs = nil
}
