// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/config.proto

package adminv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConfigIDRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConfigIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConfigIDRequestMultiError, or nil if none found.
func (m *ConfigIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := ConfigIDRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetId() <= 0 {
		err := ConfigIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConfigIDRequestMultiError(errors)
	}

	return nil
}

// ConfigIDRequestMultiError is an error wrapping multiple validation errors
// returned by ConfigIDRequest.ValidateAll() if the designated constraints
// aren't met.
type ConfigIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigIDRequestMultiError) AllErrors() []error { return m }

// ConfigIDRequestValidationError is the validation error returned by
// ConfigIDRequest.Validate if the designated constraints aren't met.
type ConfigIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigIDRequestValidationError) ErrorName() string { return "ConfigIDRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConfigIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigIDRequestValidationError{}

// Validate checks the field values on CreateConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateConfigRequestMultiError, or nil if none found.
func (m *CreateConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := CreateConfigRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetKey()); l < 1 || l > 64 {
		err := CreateConfigRequestValidationError{
			field:  "Key",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateConfigRequest_Key_Pattern.MatchString(m.GetKey()) {
		err := CreateConfigRequestValidationError{
			field:  "Key",
			reason: "value does not match regex pattern \"^[A-Za-z][A-Za-z0-9]*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := CreateConfigRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 255 {
		err := CreateConfigRequestValidationError{
			field:  "Description",
			reason: "value length must be at most 255 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateConfigRequestMultiError(errors)
	}

	return nil
}

// CreateConfigRequestMultiError is an error wrapping multiple validation
// errors returned by CreateConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateConfigRequestMultiError) AllErrors() []error { return m }

// CreateConfigRequestValidationError is the validation error returned by
// CreateConfigRequest.Validate if the designated constraints aren't met.
type CreateConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateConfigRequestValidationError) ErrorName() string {
	return "CreateConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateConfigRequestValidationError{}

var _CreateConfigRequest_Key_Pattern = regexp.MustCompile("^[A-Za-z][A-Za-z0-9]*$")

// Validate checks the field values on UpdateConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateConfigRequestMultiError, or nil if none found.
func (m *UpdateConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := UpdateConfigRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetId() <= 0 {
		err := UpdateConfigRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDescription()) > 255 {
		err := UpdateConfigRequestValidationError{
			field:  "Description",
			reason: "value length must be at most 255 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetType()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateConfigRequestValidationError{
					field:  "Type",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateConfigRequestValidationError{
					field:  "Type",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetType()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateConfigRequestValidationError{
				field:  "Type",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsArray

	// no validation rules for Version

	if len(errors) > 0 {
		return UpdateConfigRequestMultiError(errors)
	}

	return nil
}

// UpdateConfigRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateConfigRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateConfigRequestMultiError) AllErrors() []error { return m }

// UpdateConfigRequestValidationError is the validation error returned by
// UpdateConfigRequest.Validate if the designated constraints aren't met.
type UpdateConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateConfigRequestValidationError) ErrorName() string {
	return "UpdateConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateConfigRequestValidationError{}

// Validate checks the field values on UpdateConfigValueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateConfigValueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateConfigValueRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateConfigValueRequestMultiError, or nil if none found.
func (m *UpdateConfigValueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateConfigValueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := UpdateConfigValueRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetId() <= 0 {
		err := UpdateConfigValueRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Value

	// no validation rules for Version

	if len(errors) > 0 {
		return UpdateConfigValueRequestMultiError(errors)
	}

	return nil
}

// UpdateConfigValueRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateConfigValueRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateConfigValueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateConfigValueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateConfigValueRequestMultiError) AllErrors() []error { return m }

// UpdateConfigValueRequestValidationError is the validation error returned by
// UpdateConfigValueRequest.Validate if the designated constraints aren't met.
type UpdateConfigValueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateConfigValueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateConfigValueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateConfigValueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateConfigValueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateConfigValueRequestValidationError) ErrorName() string {
	return "UpdateConfigValueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateConfigValueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateConfigValueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateConfigValueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateConfigValueRequestValidationError{}

// Validate checks the field values on ListConfigRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListConfigRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConfigRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConfigRequestMultiError, or nil if none found.
func (m *ListConfigRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConfigRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := ListConfigRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Key != nil {

		if utf8.RuneCountInString(m.GetKey()) > 255 {
			err := ListConfigRequestValidationError{
				field:  "Key",
				reason: "value length must be at most 255 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ProjectId != nil {

		if m.GetProjectId() <= 0 {
			err := ListConfigRequestValidationError{
				field:  "ProjectId",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ProjectKey != nil {

		if utf8.RuneCountInString(m.GetProjectKey()) > 64 {
			err := ListConfigRequestValidationError{
				field:  "ProjectKey",
				reason: "value length must be at most 64 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return ListConfigRequestMultiError(errors)
	}

	return nil
}

// ListConfigRequestMultiError is an error wrapping multiple validation errors
// returned by ListConfigRequest.ValidateAll() if the designated constraints
// aren't met.
type ListConfigRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConfigRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConfigRequestMultiError) AllErrors() []error { return m }

// ListConfigRequestValidationError is the validation error returned by
// ListConfigRequest.Validate if the designated constraints aren't met.
type ListConfigRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConfigRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConfigRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConfigRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConfigRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConfigRequestValidationError) ErrorName() string {
	return "ListConfigRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListConfigRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConfigRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConfigRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConfigRequestValidationError{}

// Validate checks the field values on ConfigReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConfigReplyMultiError, or
// nil if none found.
func (m *ConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfigReplyValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfigReplyValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfigReplyValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConfigReplyMultiError(errors)
	}

	return nil
}

// ConfigReplyMultiError is an error wrapping multiple validation errors
// returned by ConfigReply.ValidateAll() if the designated constraints aren't met.
type ConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigReplyMultiError) AllErrors() []error { return m }

// ConfigReplyValidationError is the validation error returned by
// ConfigReply.Validate if the designated constraints aren't met.
type ConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigReplyValidationError) ErrorName() string { return "ConfigReplyValidationError" }

// Error satisfies the builtin error interface
func (e ConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigReplyValidationError{}

// Validate checks the field values on ListConfigReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConfigReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConfigReplyMultiError, or nil if none found.
func (m *ListConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListConfigReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListConfigReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListConfigReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListConfigReplyMultiError(errors)
	}

	return nil
}

// ListConfigReplyMultiError is an error wrapping multiple validation errors
// returned by ListConfigReply.ValidateAll() if the designated constraints
// aren't met.
type ListConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConfigReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConfigReplyMultiError) AllErrors() []error { return m }

// ListConfigReplyValidationError is the validation error returned by
// ListConfigReply.Validate if the designated constraints aren't met.
type ListConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConfigReplyValidationError) ErrorName() string { return "ListConfigReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConfigReplyValidationError{}

// Validate checks the field values on ListConfigItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListConfigItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConfigItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListConfigItemMultiError,
// or nil if none found.
func (m *ListConfigItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConfigItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListConfigItemValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListConfigItemValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListConfigItemValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for IsReleased

	if len(errors) > 0 {
		return ListConfigItemMultiError(errors)
	}

	return nil
}

// ListConfigItemMultiError is an error wrapping multiple validation errors
// returned by ListConfigItem.ValidateAll() if the designated constraints
// aren't met.
type ListConfigItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConfigItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConfigItemMultiError) AllErrors() []error { return m }

// ListConfigItemValidationError is the validation error returned by
// ListConfigItem.Validate if the designated constraints aren't met.
type ListConfigItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConfigItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConfigItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConfigItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConfigItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConfigItemValidationError) ErrorName() string { return "ListConfigItemValidationError" }

// Error satisfies the builtin error interface
func (e ListConfigItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConfigItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConfigItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConfigItemValidationError{}

// Validate checks the field values on ConfigDetailReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConfigDetailReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfigDetailReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConfigDetailReplyMultiError, or nil if none found.
func (m *ConfigDetailReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfigDetailReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfigDetailReplyValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfigDetailReplyValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfigDetailReplyValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTree()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConfigDetailReplyValidationError{
					field:  "Tree",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConfigDetailReplyValidationError{
					field:  "Tree",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTree()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConfigDetailReplyValidationError{
				field:  "Tree",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConfigDetailReplyMultiError(errors)
	}

	return nil
}

// ConfigDetailReplyMultiError is an error wrapping multiple validation errors
// returned by ConfigDetailReply.ValidateAll() if the designated constraints
// aren't met.
type ConfigDetailReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfigDetailReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfigDetailReplyMultiError) AllErrors() []error { return m }

// ConfigDetailReplyValidationError is the validation error returned by
// ConfigDetailReply.Validate if the designated constraints aren't met.
type ConfigDetailReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfigDetailReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfigDetailReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfigDetailReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfigDetailReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfigDetailReplyValidationError) ErrorName() string {
	return "ConfigDetailReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ConfigDetailReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfigDetailReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfigDetailReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfigDetailReplyValidationError{}
