// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/config.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConfigServiceConfigDetail = "/kirby.admin.v1.ConfigService/ConfigDetail"
const OperationConfigServiceCreateConfig = "/kirby.admin.v1.ConfigService/CreateConfig"
const OperationConfigServiceDeleteConfig = "/kirby.admin.v1.ConfigService/DeleteConfig"
const OperationConfigServiceListConfig = "/kirby.admin.v1.ConfigService/ListConfig"
const OperationConfigServiceUpdateConfig = "/kirby.admin.v1.ConfigService/UpdateConfig"
const OperationConfigServiceUpdateConfigValue = "/kirby.admin.v1.ConfigService/UpdateConfigValue"

type ConfigServiceHTTPServer interface {
	ConfigDetail(context.Context, *ConfigIDRequest) (*ConfigDetailReply, error)
	CreateConfig(context.Context, *CreateConfigRequest) (*ConfigReply, error)
	DeleteConfig(context.Context, *ConfigIDRequest) (*emptypb.Empty, error)
	ListConfig(context.Context, *ListConfigRequest) (*ListConfigReply, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*ConfigReply, error)
	UpdateConfigValue(context.Context, *UpdateConfigValueRequest) (*ConfigReply, error)
}

func RegisterConfigServiceHTTPServer(s *http.Server, srv ConfigServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/config/create", _ConfigService_CreateConfig0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/config/update", _ConfigService_UpdateConfig0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/config/updateValue", _ConfigService_UpdateConfigValue0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/config/list", _ConfigService_ListConfig0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/config/delete", _ConfigService_DeleteConfig0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/config/detail", _ConfigService_ConfigDetail0_HTTP_Handler(srv))
}

func _ConfigService_CreateConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceCreateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateConfig(ctx, req.(*CreateConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigReply)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_UpdateConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceUpdateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConfig(ctx, req.(*UpdateConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigReply)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_UpdateConfigValue0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConfigValueRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceUpdateConfigValue)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConfigValue(ctx, req.(*UpdateConfigValueRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigReply)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_ListConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceListConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConfig(ctx, req.(*ListConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConfigReply)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_DeleteConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceDeleteConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteConfig(ctx, req.(*ConfigIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ConfigService_ConfigDetail0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceConfigDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfigDetail(ctx, req.(*ConfigIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigDetailReply)
		return ctx.Result(200, reply)
	}
}

type ConfigServiceHTTPClient interface {
	ConfigDetail(ctx context.Context, req *ConfigIDRequest, opts ...http.CallOption) (rsp *ConfigDetailReply, err error)
	CreateConfig(ctx context.Context, req *CreateConfigRequest, opts ...http.CallOption) (rsp *ConfigReply, err error)
	DeleteConfig(ctx context.Context, req *ConfigIDRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListConfig(ctx context.Context, req *ListConfigRequest, opts ...http.CallOption) (rsp *ListConfigReply, err error)
	UpdateConfig(ctx context.Context, req *UpdateConfigRequest, opts ...http.CallOption) (rsp *ConfigReply, err error)
	UpdateConfigValue(ctx context.Context, req *UpdateConfigValueRequest, opts ...http.CallOption) (rsp *ConfigReply, err error)
}

type ConfigServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigServiceHTTPClient(client *http.Client) ConfigServiceHTTPClient {
	return &ConfigServiceHTTPClientImpl{client}
}

func (c *ConfigServiceHTTPClientImpl) ConfigDetail(ctx context.Context, in *ConfigIDRequest, opts ...http.CallOption) (*ConfigDetailReply, error) {
	var out ConfigDetailReply
	pattern := "/admin/environments/{environment_id}/config/detail"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceConfigDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...http.CallOption) (*ConfigReply, error) {
	var out ConfigReply
	pattern := "/admin/environments/{environment_id}/config/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceCreateConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) DeleteConfig(ctx context.Context, in *ConfigIDRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/environments/{environment_id}/config/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceDeleteConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) ListConfig(ctx context.Context, in *ListConfigRequest, opts ...http.CallOption) (*ListConfigReply, error) {
	var out ListConfigReply
	pattern := "/admin/environments/{environment_id}/config/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceListConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...http.CallOption) (*ConfigReply, error) {
	var out ConfigReply
	pattern := "/admin/environments/{environment_id}/config/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceUpdateConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConfigServiceHTTPClientImpl) UpdateConfigValue(ctx context.Context, in *UpdateConfigValueRequest, opts ...http.CallOption) (*ConfigReply, error) {
	var out ConfigReply
	pattern := "/admin/environments/{environment_id}/config/updateValue"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigServiceUpdateConfigValue))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
