// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/environment.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEnvironmentServiceCreateEnvironment = "/kirby.admin.v1.EnvironmentService/CreateEnvironment"
const OperationEnvironmentServiceListEnvironmentUsers = "/kirby.admin.v1.EnvironmentService/ListEnvironmentUsers"
const OperationEnvironmentServiceListEnvironments = "/kirby.admin.v1.EnvironmentService/ListEnvironments"
const OperationEnvironmentServiceMyPermissions = "/kirby.admin.v1.EnvironmentService/MyPermissions"
const OperationEnvironmentServiceUpdateEnvironment = "/kirby.admin.v1.EnvironmentService/UpdateEnvironment"
const OperationEnvironmentServiceUpdateEnvironmentUserRoles = "/kirby.admin.v1.EnvironmentService/UpdateEnvironmentUserRoles"

type EnvironmentServiceHTTPServer interface {
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*EnvironmentReply, error)
	ListEnvironmentUsers(context.Context, *EnvironmentIDRequest) (*ListEnvironmentUsersReply, error)
	ListEnvironments(context.Context, *ListEnvironmentsRequest) (*ListEnvironmentsReply, error)
	MyPermissions(context.Context, *EnvironmentIDRequest) (*MyPermissionsReply, error)
	UpdateEnvironment(context.Context, *UpdateEnvironmentRequest) (*EnvironmentReply, error)
	UpdateEnvironmentUserRoles(context.Context, *UpdateEnvironmentUserRolesRequest) (*emptypb.Empty, error)
}

func RegisterEnvironmentServiceHTTPServer(s *http.Server, srv EnvironmentServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/environments", _EnvironmentService_ListEnvironments0_HTTP_Handler(srv))
	r.POST("/admin/projects/{project_id}/environments", _EnvironmentService_CreateEnvironment0_HTTP_Handler(srv))
	r.PUT("/admin/projects/{project_id}/environments/{environment_id}", _EnvironmentService_UpdateEnvironment0_HTTP_Handler(srv))
	r.GET("/admin/environments/{environment_id}/my-permissions", _EnvironmentService_MyPermissions0_HTTP_Handler(srv))
	r.GET("/admin/environments/{environment_id}/users", _EnvironmentService_ListEnvironmentUsers0_HTTP_Handler(srv))
	r.PUT("/admin/environments/{environment_id}/users/{user_id}/roles", _EnvironmentService_UpdateEnvironmentUserRoles0_HTTP_Handler(srv))
}

func _EnvironmentService_ListEnvironments0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEnvironmentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceListEnvironments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnvironments(ctx, req.(*ListEnvironmentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEnvironmentsReply)
		return ctx.Result(200, reply)
	}
}

func _EnvironmentService_CreateEnvironment0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEnvironmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceCreateEnvironment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnvironmentReply)
		return ctx.Result(200, reply)
	}
}

func _EnvironmentService_UpdateEnvironment0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEnvironmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceUpdateEnvironment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEnvironment(ctx, req.(*UpdateEnvironmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EnvironmentReply)
		return ctx.Result(200, reply)
	}
}

func _EnvironmentService_MyPermissions0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnvironmentIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceMyPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MyPermissions(ctx, req.(*EnvironmentIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MyPermissionsReply)
		return ctx.Result(200, reply)
	}
}

func _EnvironmentService_ListEnvironmentUsers0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnvironmentIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceListEnvironmentUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnvironmentUsers(ctx, req.(*EnvironmentIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEnvironmentUsersReply)
		return ctx.Result(200, reply)
	}
}

func _EnvironmentService_UpdateEnvironmentUserRoles0_HTTP_Handler(srv EnvironmentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEnvironmentUserRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEnvironmentServiceUpdateEnvironmentUserRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEnvironmentUserRoles(ctx, req.(*UpdateEnvironmentUserRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type EnvironmentServiceHTTPClient interface {
	CreateEnvironment(ctx context.Context, req *CreateEnvironmentRequest, opts ...http.CallOption) (rsp *EnvironmentReply, err error)
	ListEnvironmentUsers(ctx context.Context, req *EnvironmentIDRequest, opts ...http.CallOption) (rsp *ListEnvironmentUsersReply, err error)
	ListEnvironments(ctx context.Context, req *ListEnvironmentsRequest, opts ...http.CallOption) (rsp *ListEnvironmentsReply, err error)
	MyPermissions(ctx context.Context, req *EnvironmentIDRequest, opts ...http.CallOption) (rsp *MyPermissionsReply, err error)
	UpdateEnvironment(ctx context.Context, req *UpdateEnvironmentRequest, opts ...http.CallOption) (rsp *EnvironmentReply, err error)
	UpdateEnvironmentUserRoles(ctx context.Context, req *UpdateEnvironmentUserRolesRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type EnvironmentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEnvironmentServiceHTTPClient(client *http.Client) EnvironmentServiceHTTPClient {
	return &EnvironmentServiceHTTPClientImpl{client}
}

func (c *EnvironmentServiceHTTPClientImpl) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...http.CallOption) (*EnvironmentReply, error) {
	var out EnvironmentReply
	pattern := "/admin/projects/{project_id}/environments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEnvironmentServiceCreateEnvironment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EnvironmentServiceHTTPClientImpl) ListEnvironmentUsers(ctx context.Context, in *EnvironmentIDRequest, opts ...http.CallOption) (*ListEnvironmentUsersReply, error) {
	var out ListEnvironmentUsersReply
	pattern := "/admin/environments/{environment_id}/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEnvironmentServiceListEnvironmentUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EnvironmentServiceHTTPClientImpl) ListEnvironments(ctx context.Context, in *ListEnvironmentsRequest, opts ...http.CallOption) (*ListEnvironmentsReply, error) {
	var out ListEnvironmentsReply
	pattern := "/admin/environments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEnvironmentServiceListEnvironments))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EnvironmentServiceHTTPClientImpl) MyPermissions(ctx context.Context, in *EnvironmentIDRequest, opts ...http.CallOption) (*MyPermissionsReply, error) {
	var out MyPermissionsReply
	pattern := "/admin/environments/{environment_id}/my-permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEnvironmentServiceMyPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EnvironmentServiceHTTPClientImpl) UpdateEnvironment(ctx context.Context, in *UpdateEnvironmentRequest, opts ...http.CallOption) (*EnvironmentReply, error) {
	var out EnvironmentReply
	pattern := "/admin/projects/{project_id}/environments/{environment_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEnvironmentServiceUpdateEnvironment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EnvironmentServiceHTTPClientImpl) UpdateEnvironmentUserRoles(ctx context.Context, in *UpdateEnvironmentUserRolesRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/environments/{environment_id}/users/{user_id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEnvironmentServiceUpdateEnvironmentUserRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
