// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/project.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnvironmentId *int64                 `protobuf:"varint,2,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectIDRequest) Reset() {
	*x = ProjectIDRequest{}
	mi := &file_admin_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectIDRequest) ProtoMessage() {}

func (x *ProjectIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectIDRequest.ProtoReflect.Descriptor instead.
func (*ProjectIDRequest) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectIDRequest) GetEnvironmentId() int64 {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return 0
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_admin_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_admin_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	EnvironmentId *int64                 `protobuf:"varint,2,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectRequest) Reset() {
	*x = ListProjectRequest{}
	mi := &file_admin_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectRequest) ProtoMessage() {}

func (x *ListProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectRequest.ProtoReflect.Descriptor instead.
func (*ListProjectRequest) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProjectRequest) GetEnvironmentId() int64 {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return 0
}

type ProjectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *common.Project        `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectReply) Reset() {
	*x = ProjectReply{}
	mi := &file_admin_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectReply) ProtoMessage() {}

func (x *ProjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectReply.ProtoReflect.Descriptor instead.
func (*ProjectReply) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectReply) GetProject() *common.Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ListProjectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*common.Project      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectReply) Reset() {
	*x = ListProjectReply{}
	mi := &file_admin_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectReply) ProtoMessage() {}

func (x *ListProjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectReply.ProtoReflect.Descriptor instead.
func (*ListProjectReply) Descriptor() ([]byte, []int) {
	return file_admin_project_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectReply) GetList() []*common.Project {
	if x != nil {
		return x.List
	}
	return nil
}

var File_admin_project_proto protoreflect.FileDescriptor

const file_admin_project_proto_rawDesc = "" +
	"\n" +
	"\x13admin/project.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/entity.proto\x1a\x17validate/validate.proto\"s\n" +
	"\x10ProjectIDRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x123\n" +
	"\x0eenvironment_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00H\x00R\renvironmentId\x88\x01\x01B\x11\n" +
	"\x0f_environment_id\"\x96\x01\n" +
	"\x14CreateProjectRequest\x123\n" +
	"\x03key\x18\x01 \x01(\tB!\xfaB\x1er\x1c\x10\x01\x18@2\x16^[A-Za-z][A-Za-z0-9]*$R\x03key\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\vdescription\"\x94\x01\n" +
	"\x14UpdateProjectRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\vdescription\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\x7f\n" +
	"\x12ListProjectRequest\x12!\n" +
	"\akeyword\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x18@R\akeyword\x123\n" +
	"\x0eenvironment_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00H\x00R\renvironmentId\x88\x01\x01B\x11\n" +
	"\x0f_environment_id\"B\n" +
	"\fProjectReply\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.kirby.common.v1.ProjectR\aproject\"@\n" +
	"\x10ListProjectReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.kirby.common.v1.ProjectR\x04list2\xd4\x03\n" +
	"\x0eProjectService\x12o\n" +
	"\rCreateProject\x12$.kirby.admin.v1.CreateProjectRequest\x1a\x1c.kirby.admin.v1.ProjectReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/projects\x12t\n" +
	"\rUpdateProject\x12$.kirby.admin.v1.UpdateProjectRequest\x1a\x1c.kirby.admin.v1.ProjectReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/admin/projects/{id}\x12l\n" +
	"\vListProject\x12\".kirby.admin.v1.ListProjectRequest\x1a .kirby.admin.v1.ListProjectReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/admin/projects\x12m\n" +
	"\rProjectDetail\x12 .kirby.admin.v1.ProjectIDRequest\x1a\x1c.kirby.admin.v1.ProjectReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/admin/projects/{id}B2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_project_proto_rawDescOnce sync.Once
	file_admin_project_proto_rawDescData []byte
)

func file_admin_project_proto_rawDescGZIP() []byte {
	file_admin_project_proto_rawDescOnce.Do(func() {
		file_admin_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_project_proto_rawDesc), len(file_admin_project_proto_rawDesc)))
	})
	return file_admin_project_proto_rawDescData
}

var file_admin_project_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_project_proto_goTypes = []any{
	(*ProjectIDRequest)(nil),     // 0: kirby.admin.v1.ProjectIDRequest
	(*CreateProjectRequest)(nil), // 1: kirby.admin.v1.CreateProjectRequest
	(*UpdateProjectRequest)(nil), // 2: kirby.admin.v1.UpdateProjectRequest
	(*ListProjectRequest)(nil),   // 3: kirby.admin.v1.ListProjectRequest
	(*ProjectReply)(nil),         // 4: kirby.admin.v1.ProjectReply
	(*ListProjectReply)(nil),     // 5: kirby.admin.v1.ListProjectReply
	(*common.Project)(nil),       // 6: kirby.common.v1.Project
}
var file_admin_project_proto_depIdxs = []int32{
	6, // 0: kirby.admin.v1.ProjectReply.project:type_name -> kirby.common.v1.Project
	6, // 1: kirby.admin.v1.ListProjectReply.list:type_name -> kirby.common.v1.Project
	1, // 2: kirby.admin.v1.ProjectService.CreateProject:input_type -> kirby.admin.v1.CreateProjectRequest
	2, // 3: kirby.admin.v1.ProjectService.UpdateProject:input_type -> kirby.admin.v1.UpdateProjectRequest
	3, // 4: kirby.admin.v1.ProjectService.ListProject:input_type -> kirby.admin.v1.ListProjectRequest
	0, // 5: kirby.admin.v1.ProjectService.ProjectDetail:input_type -> kirby.admin.v1.ProjectIDRequest
	4, // 6: kirby.admin.v1.ProjectService.CreateProject:output_type -> kirby.admin.v1.ProjectReply
	4, // 7: kirby.admin.v1.ProjectService.UpdateProject:output_type -> kirby.admin.v1.ProjectReply
	5, // 8: kirby.admin.v1.ProjectService.ListProject:output_type -> kirby.admin.v1.ListProjectReply
	4, // 9: kirby.admin.v1.ProjectService.ProjectDetail:output_type -> kirby.admin.v1.ProjectReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_project_proto_init() }
func file_admin_project_proto_init() {
	if File_admin_project_proto != nil {
		return
	}
	file_admin_project_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_project_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_project_proto_rawDesc), len(file_admin_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_project_proto_goTypes,
		DependencyIndexes: file_admin_project_proto_depIdxs,
		MessageInfos:      file_admin_project_proto_msgTypes,
	}.Build()
	File_admin_project_proto = out.File
	file_admin_project_proto_goTypes = nil
	file_admin_project_proto_depIdxs = nil
}
