// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/project_api_key.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProjectApiKeyServiceCreateProjectApiKey = "/kirby.admin.v1.ProjectApiKeyService/CreateProjectApiKey"
const OperationProjectApiKeyServiceListProjectApiKeys = "/kirby.admin.v1.ProjectApiKeyService/ListProjectApiKeys"
const OperationProjectApiKeyServiceRevokeProjectApiKey = "/kirby.admin.v1.ProjectApiKeyService/RevokeProjectApiKey"
const OperationProjectApiKeyServiceRotateProjectApiKey = "/kirby.admin.v1.ProjectApiKeyService/RotateProjectApiKey"

type ProjectApiKeyServiceHTTPServer interface {
	CreateProjectApiKey(context.Context, *CreateProjectApiKeyRequest) (*ProjectApiKeySecretReply, error)
	ListProjectApiKeys(context.Context, *ProjectApiKeyScopeRequest) (*ListProjectApiKeysReply, error)
	RevokeProjectApiKey(context.Context, *ProjectApiKeyIDRequest) (*emptypb.Empty, error)
	RotateProjectApiKey(context.Context, *ProjectApiKeyIDRequest) (*ProjectApiKeySecretReply, error)
}

func RegisterProjectApiKeyServiceHTTPServer(s *http.Server, srv ProjectApiKeyServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/environments/{environment_id}/projects/{project_id}/api-keys", _ProjectApiKeyService_ListProjectApiKeys0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/projects/{project_id}/api-keys", _ProjectApiKeyService_CreateProjectApiKey0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/projects/{project_id}/api-keys/{key_id}/rotate", _ProjectApiKeyService_RotateProjectApiKey0_HTTP_Handler(srv))
	r.DELETE("/admin/environments/{environment_id}/projects/{project_id}/api-keys/{key_id}", _ProjectApiKeyService_RevokeProjectApiKey0_HTTP_Handler(srv))
}

func _ProjectApiKeyService_ListProjectApiKeys0_HTTP_Handler(srv ProjectApiKeyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProjectApiKeyScopeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectApiKeyServiceListProjectApiKeys)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProjectApiKeys(ctx, req.(*ProjectApiKeyScopeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectApiKeysReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectApiKeyService_CreateProjectApiKey0_HTTP_Handler(srv ProjectApiKeyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProjectApiKeyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectApiKeyServiceCreateProjectApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProjectApiKey(ctx, req.(*CreateProjectApiKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectApiKeySecretReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectApiKeyService_RotateProjectApiKey0_HTTP_Handler(srv ProjectApiKeyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProjectApiKeyIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectApiKeyServiceRotateProjectApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RotateProjectApiKey(ctx, req.(*ProjectApiKeyIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectApiKeySecretReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectApiKeyService_RevokeProjectApiKey0_HTTP_Handler(srv ProjectApiKeyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProjectApiKeyIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectApiKeyServiceRevokeProjectApiKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeProjectApiKey(ctx, req.(*ProjectApiKeyIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ProjectApiKeyServiceHTTPClient interface {
	CreateProjectApiKey(ctx context.Context, req *CreateProjectApiKeyRequest, opts ...http.CallOption) (rsp *ProjectApiKeySecretReply, err error)
	ListProjectApiKeys(ctx context.Context, req *ProjectApiKeyScopeRequest, opts ...http.CallOption) (rsp *ListProjectApiKeysReply, err error)
	RevokeProjectApiKey(ctx context.Context, req *ProjectApiKeyIDRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RotateProjectApiKey(ctx context.Context, req *ProjectApiKeyIDRequest, opts ...http.CallOption) (rsp *ProjectApiKeySecretReply, err error)
}

type ProjectApiKeyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProjectApiKeyServiceHTTPClient(client *http.Client) ProjectApiKeyServiceHTTPClient {
	return &ProjectApiKeyServiceHTTPClientImpl{client}
}

func (c *ProjectApiKeyServiceHTTPClientImpl) CreateProjectApiKey(ctx context.Context, in *CreateProjectApiKeyRequest, opts ...http.CallOption) (*ProjectApiKeySecretReply, error) {
	var out ProjectApiKeySecretReply
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/api-keys"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectApiKeyServiceCreateProjectApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectApiKeyServiceHTTPClientImpl) ListProjectApiKeys(ctx context.Context, in *ProjectApiKeyScopeRequest, opts ...http.CallOption) (*ListProjectApiKeysReply, error) {
	var out ListProjectApiKeysReply
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/api-keys"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectApiKeyServiceListProjectApiKeys))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectApiKeyServiceHTTPClientImpl) RevokeProjectApiKey(ctx context.Context, in *ProjectApiKeyIDRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/api-keys/{key_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProjectApiKeyServiceRevokeProjectApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectApiKeyServiceHTTPClientImpl) RotateProjectApiKey(ctx context.Context, in *ProjectApiKeyIDRequest, opts ...http.CallOption) (*ProjectApiKeySecretReply, error) {
	var out ProjectApiKeySecretReply
	pattern := "/admin/environments/{environment_id}/projects/{project_id}/api-keys/{key_id}/rotate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectApiKeyServiceRotateProjectApiKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
