// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/project_api_key.proto

package adminv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectApiKeyScopeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectApiKeyScopeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectApiKeyScopeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectApiKeyScopeRequestMultiError, or nil if none found.
func (m *ProjectApiKeyScopeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectApiKeyScopeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := ProjectApiKeyScopeRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := ProjectApiKeyScopeRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectApiKeyScopeRequestMultiError(errors)
	}

	return nil
}

// ProjectApiKeyScopeRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectApiKeyScopeRequest.ValidateAll() if the
// designated constraints aren't met.
type ProjectApiKeyScopeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectApiKeyScopeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectApiKeyScopeRequestMultiError) AllErrors() []error { return m }

// ProjectApiKeyScopeRequestValidationError is the validation error returned by
// ProjectApiKeyScopeRequest.Validate if the designated constraints aren't met.
type ProjectApiKeyScopeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectApiKeyScopeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectApiKeyScopeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectApiKeyScopeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectApiKeyScopeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectApiKeyScopeRequestValidationError) ErrorName() string {
	return "ProjectApiKeyScopeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectApiKeyScopeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectApiKeyScopeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectApiKeyScopeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectApiKeyScopeRequestValidationError{}

// Validate checks the field values on ProjectApiKeyIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectApiKeyIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectApiKeyIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectApiKeyIDRequestMultiError, or nil if none found.
func (m *ProjectApiKeyIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectApiKeyIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := ProjectApiKeyIDRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := ProjectApiKeyIDRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetKeyId() <= 0 {
		err := ProjectApiKeyIDRequestValidationError{
			field:  "KeyId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectApiKeyIDRequestMultiError(errors)
	}

	return nil
}

// ProjectApiKeyIDRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectApiKeyIDRequest.ValidateAll() if the designated
// constraints aren't met.
type ProjectApiKeyIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectApiKeyIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectApiKeyIDRequestMultiError) AllErrors() []error { return m }

// ProjectApiKeyIDRequestValidationError is the validation error returned by
// ProjectApiKeyIDRequest.Validate if the designated constraints aren't met.
type ProjectApiKeyIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectApiKeyIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectApiKeyIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectApiKeyIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectApiKeyIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectApiKeyIDRequestValidationError) ErrorName() string {
	return "ProjectApiKeyIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectApiKeyIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectApiKeyIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectApiKeyIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectApiKeyIDRequestValidationError{}

// Validate checks the field values on CreateProjectApiKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateProjectApiKeyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateProjectApiKeyRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateProjectApiKeyRequestMultiError, or nil if none found.
func (m *CreateProjectApiKeyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateProjectApiKeyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEnvironmentId() <= 0 {
		err := CreateProjectApiKeyRequestValidationError{
			field:  "EnvironmentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetProjectId() <= 0 {
		err := CreateProjectApiKeyRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 64 {
		err := CreateProjectApiKeyRequestValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateProjectApiKeyRequestMultiError(errors)
	}

	return nil
}

// CreateProjectApiKeyRequestMultiError is an error wrapping multiple
// validation errors returned by CreateProjectApiKeyRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateProjectApiKeyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateProjectApiKeyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateProjectApiKeyRequestMultiError) AllErrors() []error { return m }

// CreateProjectApiKeyRequestValidationError is the validation error returned
// by CreateProjectApiKeyRequest.Validate if the designated constraints aren't met.
type CreateProjectApiKeyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateProjectApiKeyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateProjectApiKeyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateProjectApiKeyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateProjectApiKeyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateProjectApiKeyRequestValidationError) ErrorName() string {
	return "CreateProjectApiKeyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateProjectApiKeyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateProjectApiKeyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateProjectApiKeyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateProjectApiKeyRequestValidationError{}

// Validate checks the field values on ListProjectApiKeysReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProjectApiKeysReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProjectApiKeysReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProjectApiKeysReplyMultiError, or nil if none found.
func (m *ListProjectApiKeysReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProjectApiKeysReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProjectApiKeysReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProjectApiKeysReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProjectApiKeysReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListProjectApiKeysReplyMultiError(errors)
	}

	return nil
}

// ListProjectApiKeysReplyMultiError is an error wrapping multiple validation
// errors returned by ListProjectApiKeysReply.ValidateAll() if the designated
// constraints aren't met.
type ListProjectApiKeysReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProjectApiKeysReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProjectApiKeysReplyMultiError) AllErrors() []error { return m }

// ListProjectApiKeysReplyValidationError is the validation error returned by
// ListProjectApiKeysReply.Validate if the designated constraints aren't met.
type ListProjectApiKeysReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProjectApiKeysReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProjectApiKeysReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProjectApiKeysReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProjectApiKeysReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProjectApiKeysReplyValidationError) ErrorName() string {
	return "ListProjectApiKeysReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListProjectApiKeysReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProjectApiKeysReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProjectApiKeysReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProjectApiKeysReplyValidationError{}

// Validate checks the field values on ProjectApiKeySecretReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectApiKeySecretReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectApiKeySecretReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectApiKeySecretReplyMultiError, or nil if none found.
func (m *ProjectApiKeySecretReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectApiKeySecretReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetApiKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProjectApiKeySecretReplyValidationError{
					field:  "ApiKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProjectApiKeySecretReplyValidationError{
					field:  "ApiKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetApiKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectApiKeySecretReplyValidationError{
				field:  "ApiKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Secret

	if len(errors) > 0 {
		return ProjectApiKeySecretReplyMultiError(errors)
	}

	return nil
}

// ProjectApiKeySecretReplyMultiError is an error wrapping multiple validation
// errors returned by ProjectApiKeySecretReply.ValidateAll() if the designated
// constraints aren't met.
type ProjectApiKeySecretReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectApiKeySecretReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectApiKeySecretReplyMultiError) AllErrors() []error { return m }

// ProjectApiKeySecretReplyValidationError is the validation error returned by
// ProjectApiKeySecretReply.Validate if the designated constraints aren't met.
type ProjectApiKeySecretReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectApiKeySecretReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectApiKeySecretReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectApiKeySecretReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectApiKeySecretReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectApiKeySecretReplyValidationError) ErrorName() string {
	return "ProjectApiKeySecretReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectApiKeySecretReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectApiKeySecretReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectApiKeySecretReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectApiKeySecretReplyValidationError{}
