// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/project.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProjectServiceCreateProject = "/kirby.admin.v1.ProjectService/CreateProject"
const OperationProjectServiceListProject = "/kirby.admin.v1.ProjectService/ListProject"
const OperationProjectServiceProjectDetail = "/kirby.admin.v1.ProjectService/ProjectDetail"
const OperationProjectServiceUpdateProject = "/kirby.admin.v1.ProjectService/UpdateProject"

type ProjectServiceHTTPServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectReply, error)
	ListProject(context.Context, *ListProjectRequest) (*ListProjectReply, error)
	ProjectDetail(context.Context, *ProjectIDRequest) (*ProjectReply, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectReply, error)
}

func RegisterProjectServiceHTTPServer(s *http.Server, srv ProjectServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/project/create", _ProjectService_CreateProject0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/project/update", _ProjectService_UpdateProject0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/project/list", _ProjectService_ListProject0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/project/detail", _ProjectService_ProjectDetail0_HTTP_Handler(srv))
}

func _ProjectService_CreateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceCreateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProject(ctx, req.(*CreateProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_UpdateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceUpdateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProject(ctx, req.(*UpdateProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ListProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProject(ctx, req.(*ListProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ProjectDetail0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProjectIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceProjectDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ProjectDetail(ctx, req.(*ProjectIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectReply)
		return ctx.Result(200, reply)
	}
}

type ProjectServiceHTTPClient interface {
	CreateProject(ctx context.Context, req *CreateProjectRequest, opts ...http.CallOption) (rsp *ProjectReply, err error)
	ListProject(ctx context.Context, req *ListProjectRequest, opts ...http.CallOption) (rsp *ListProjectReply, err error)
	ProjectDetail(ctx context.Context, req *ProjectIDRequest, opts ...http.CallOption) (rsp *ProjectReply, err error)
	UpdateProject(ctx context.Context, req *UpdateProjectRequest, opts ...http.CallOption) (rsp *ProjectReply, err error)
}

type ProjectServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProjectServiceHTTPClient(client *http.Client) ProjectServiceHTTPClient {
	return &ProjectServiceHTTPClientImpl{client}
}

func (c *ProjectServiceHTTPClientImpl) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...http.CallOption) (*ProjectReply, error) {
	var out ProjectReply
	pattern := "/admin/environments/{environment_id}/project/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceCreateProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListProject(ctx context.Context, in *ListProjectRequest, opts ...http.CallOption) (*ListProjectReply, error) {
	var out ListProjectReply
	pattern := "/admin/environments/{environment_id}/project/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceListProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ProjectDetail(ctx context.Context, in *ProjectIDRequest, opts ...http.CallOption) (*ProjectReply, error) {
	var out ProjectReply
	pattern := "/admin/environments/{environment_id}/project/detail"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceProjectDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...http.CallOption) (*ProjectReply, error) {
	var out ProjectReply
	pattern := "/admin/environments/{environment_id}/project/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProjectServiceUpdateProject))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
