// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/publication.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPublicationServicePublishSnapshot = "/kirby.admin.v1.PublicationService/PublishSnapshot"
const OperationPublicationServiceUnpublishSnapshot = "/kirby.admin.v1.PublicationService/UnpublishSnapshot"

type PublicationServiceHTTPServer interface {
	PublishSnapshot(context.Context, *PublishSnapshotRequest) (*SnapshotReply, error)
	UnpublishSnapshot(context.Context, *PublishSnapshotRequest) (*SnapshotReply, error)
}

func RegisterPublicationServiceHTTPServer(s *http.Server, srv PublicationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/snapshots/{snapshot_id}/publish", _PublicationService_PublishSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshots/{snapshot_id}/unpublish", _PublicationService_UnpublishSnapshot0_HTTP_Handler(srv))
}

func _PublicationService_PublishSnapshot0_HTTP_Handler(srv PublicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicationServicePublishSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishSnapshot(ctx, req.(*PublishSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _PublicationService_UnpublishSnapshot0_HTTP_Handler(srv PublicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublicationServiceUnpublishSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnpublishSnapshot(ctx, req.(*PublishSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

type PublicationServiceHTTPClient interface {
	PublishSnapshot(ctx context.Context, req *PublishSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
	UnpublishSnapshot(ctx context.Context, req *PublishSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
}

type PublicationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPublicationServiceHTTPClient(client *http.Client) PublicationServiceHTTPClient {
	return &PublicationServiceHTTPClientImpl{client}
}

func (c *PublicationServiceHTTPClientImpl) PublishSnapshot(ctx context.Context, in *PublishSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshots/{snapshot_id}/publish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicationServicePublishSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PublicationServiceHTTPClientImpl) UnpublishSnapshot(ctx context.Context, in *PublishSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshots/{snapshot_id}/unpublish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublicationServiceUnpublishSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
