// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/snapshot.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSnapshotServiceCreateSnapshot = "/kirby.admin.v1.SnapshotService/CreateSnapshot"
const OperationSnapshotServiceCurrentSnapshot = "/kirby.admin.v1.SnapshotService/CurrentSnapshot"
const OperationSnapshotServiceDeleteSnapshot = "/kirby.admin.v1.SnapshotService/DeleteSnapshot"
const OperationSnapshotServiceGetSnapshot = "/kirby.admin.v1.SnapshotService/GetSnapshot"
const OperationSnapshotServiceListSnapshot = "/kirby.admin.v1.SnapshotService/ListSnapshot"
const OperationSnapshotServiceLoadSnapshot = "/kirby.admin.v1.SnapshotService/LoadSnapshot"
const OperationSnapshotServicePreviewCreatingSnapshot = "/kirby.admin.v1.SnapshotService/PreviewCreatingSnapshot"
const OperationSnapshotServiceReleasedSnapshot = "/kirby.admin.v1.SnapshotService/ReleasedSnapshot"

type SnapshotServiceHTTPServer interface {
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*SnapshotReply, error)
	CurrentSnapshot(context.Context, *ConfigSnapshotRequest) (*SnapshotReply, error)
	DeleteSnapshot(context.Context, *SnapshotIDRequest) (*emptypb.Empty, error)
	GetSnapshot(context.Context, *SnapshotIDRequest) (*SnapshotReply, error)
	ListSnapshot(context.Context, *ListSnapshotRequest) (*ListSnapshotReply, error)
	LoadSnapshot(context.Context, *LoadSnapshotRequest) (*SnapshotReply, error)
	PreviewCreatingSnapshot(context.Context, *ConfigSnapshotRequest) (*PreviewCreatingSnapshotReply, error)
	ReleasedSnapshot(context.Context, *ConfigSnapshotRequest) (*SnapshotReply, error)
}

func RegisterSnapshotServiceHTTPServer(s *http.Server, srv SnapshotServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/snapshot/create", _SnapshotService_CreateSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/previewCreating", _SnapshotService_PreviewCreatingSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/delete", _SnapshotService_DeleteSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/detail", _SnapshotService_GetSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/load", _SnapshotService_LoadSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/current", _SnapshotService_CurrentSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/released", _SnapshotService_ReleasedSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/snapshot/list", _SnapshotService_ListSnapshot0_HTTP_Handler(srv))
}

func _SnapshotService_CreateSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceCreateSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_PreviewCreatingSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServicePreviewCreatingSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewCreatingSnapshot(ctx, req.(*ConfigSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewCreatingSnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_DeleteSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SnapshotIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceDeleteSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSnapshot(ctx, req.(*SnapshotIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_GetSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SnapshotIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceGetSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSnapshot(ctx, req.(*SnapshotIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_LoadSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoadSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceLoadSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoadSnapshot(ctx, req.(*LoadSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_CurrentSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceCurrentSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CurrentSnapshot(ctx, req.(*ConfigSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_ReleasedSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceReleasedSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReleasedSnapshot(ctx, req.(*ConfigSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotService_ListSnapshot0_HTTP_Handler(srv SnapshotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotServiceListSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSnapshot(ctx, req.(*ListSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSnapshotReply)
		return ctx.Result(200, reply)
	}
}

type SnapshotServiceHTTPClient interface {
	CreateSnapshot(ctx context.Context, req *CreateSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
	CurrentSnapshot(ctx context.Context, req *ConfigSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
	DeleteSnapshot(ctx context.Context, req *SnapshotIDRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetSnapshot(ctx context.Context, req *SnapshotIDRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
	ListSnapshot(ctx context.Context, req *ListSnapshotRequest, opts ...http.CallOption) (rsp *ListSnapshotReply, err error)
	LoadSnapshot(ctx context.Context, req *LoadSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
	PreviewCreatingSnapshot(ctx context.Context, req *ConfigSnapshotRequest, opts ...http.CallOption) (rsp *PreviewCreatingSnapshotReply, err error)
	ReleasedSnapshot(ctx context.Context, req *ConfigSnapshotRequest, opts ...http.CallOption) (rsp *SnapshotReply, err error)
}

type SnapshotServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSnapshotServiceHTTPClient(client *http.Client) SnapshotServiceHTTPClient {
	return &SnapshotServiceHTTPClientImpl{client}
}

func (c *SnapshotServiceHTTPClientImpl) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceCreateSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) CurrentSnapshot(ctx context.Context, in *ConfigSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/current"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceCurrentSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) DeleteSnapshot(ctx context.Context, in *SnapshotIDRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/environments/{environment_id}/snapshot/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceDeleteSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) GetSnapshot(ctx context.Context, in *SnapshotIDRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/detail"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceGetSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) ListSnapshot(ctx context.Context, in *ListSnapshotRequest, opts ...http.CallOption) (*ListSnapshotReply, error) {
	var out ListSnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceListSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) LoadSnapshot(ctx context.Context, in *LoadSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/load"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceLoadSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) PreviewCreatingSnapshot(ctx context.Context, in *ConfigSnapshotRequest, opts ...http.CallOption) (*PreviewCreatingSnapshotReply, error) {
	var out PreviewCreatingSnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/previewCreating"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServicePreviewCreatingSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotServiceHTTPClientImpl) ReleasedSnapshot(ctx context.Context, in *ConfigSnapshotRequest, opts ...http.CallOption) (*SnapshotReply, error) {
	var out SnapshotReply
	pattern := "/admin/environments/{environment_id}/snapshot/released"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotServiceReleasedSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
