// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/snapshot.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotIDRequest) Reset() {
	*x = SnapshotIDRequest{}
	mi := &file_admin_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotIDRequest) ProtoMessage() {}

func (x *SnapshotIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotIDRequest.ProtoReflect.Descriptor instead.
func (*SnapshotIDRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotIDRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *SnapshotIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConfigSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshotRequest) Reset() {
	*x = ConfigSnapshotRequest{}
	mi := &file_admin_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshotRequest) ProtoMessage() {}

func (x *ConfigSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ConfigSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSnapshotRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *ConfigSnapshotRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []common.Snapshot_Tag  `protobuf:"varint,5,rep,packed,name=tags,proto3,enum=kirby.common.v1.Snapshot_Tag" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_admin_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSnapshotRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CreateSnapshotRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *CreateSnapshotRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *CreateSnapshotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSnapshotRequest) GetTags() []common.Snapshot_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type LoadSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSnapshotRequest) Reset() {
	*x = LoadSnapshotRequest{}
	mi := &file_admin_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSnapshotRequest) ProtoMessage() {}

func (x *LoadSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSnapshotRequest.ProtoReflect.Descriptor instead.
func (*LoadSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *LoadSnapshotRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *LoadSnapshotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoadSnapshotRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

type ListSnapshotRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	EnvironmentId int64                     `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConfigId      int64                     `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ProjectId     int64                     `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Page          *common.PaginationRequest `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotRequest) Reset() {
	*x = ListSnapshotRequest{}
	mi := &file_admin_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotRequest) ProtoMessage() {}

func (x *ListSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *ListSnapshotRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *ListSnapshotRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ListSnapshotRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListSnapshotRequest) GetPage() *common.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *common.Snapshot       `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotReply) Reset() {
	*x = SnapshotReply{}
	mi := &file_admin_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotReply) ProtoMessage() {}

func (x *SnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotReply.ProtoReflect.Descriptor instead.
func (*SnapshotReply) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotReply) GetSnapshot() *common.Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type PreviewCreatingSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewCreatingSnapshotReply) Reset() {
	*x = PreviewCreatingSnapshotReply{}
	mi := &file_admin_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewCreatingSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewCreatingSnapshotReply) ProtoMessage() {}

func (x *PreviewCreatingSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewCreatingSnapshotReply.ProtoReflect.Descriptor instead.
func (*PreviewCreatingSnapshotReply) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *PreviewCreatingSnapshotReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListSnapshotReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Page          *common.Pagination       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	List          []*common.SimpleSnapshot `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotReply) Reset() {
	*x = ListSnapshotReply{}
	mi := &file_admin_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotReply) ProtoMessage() {}

func (x *ListSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotReply.ProtoReflect.Descriptor instead.
func (*ListSnapshotReply) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *ListSnapshotReply) GetPage() *common.Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListSnapshotReply) GetList() []*common.SimpleSnapshot {
	if x != nil {
		return x.List
	}
	return nil
}

var File_admin_snapshot_proto protoreflect.FileDescriptor

const file_admin_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x14admin/snapshot.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/entity.proto\x1a\x12common/types.proto\x1a\x17validate/validate.proto\"\\\n" +
	"\x11SnapshotIDRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"m\n" +
	"\x15ConfigSnapshotRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12$\n" +
	"\tconfig_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\"\xf6\x01\n" +
	"\x15CreateSnapshotRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12$\n" +
	"\tconfig_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\x12&\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tprojectId\x12,\n" +
	"\vdescription\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xff\x01R\vdescription\x121\n" +
	"\x04tags\x18\x05 \x03(\x0e2\x1d.kirby.common.v1.Snapshot.TagR\x04tags\"\x84\x01\n" +
	"\x13LoadSnapshotRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12$\n" +
	"\tconfig_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\"\xcb\x01\n" +
	"\x13ListSnapshotRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12$\n" +
	"\tconfig_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\x12&\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tprojectId\x126\n" +
	"\x04page\x18\x04 \x01(\v2\".kirby.common.v1.PaginationRequestR\x04page\"F\n" +
	"\rSnapshotReply\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.kirby.common.v1.SnapshotR\bsnapshot\"8\n" +
	"\x1cPreviewCreatingSnapshotReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"y\n" +
	"\x11ListSnapshotReply\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.kirby.common.v1.PaginationR\x04page\x123\n" +
	"\x04list\x18\x02 \x03(\v2\x1f.kirby.common.v1.SimpleSnapshotR\x04list2\xee\t\n" +
	"\x0fSnapshotService\x12\x97\x01\n" +
	"\x0eCreateSnapshot\x12%.kirby.admin.v1.CreateSnapshotRequest\x1a\x1d.kirby.admin.v1.SnapshotReply\"?\x82\xd3\xe4\x93\x029:\x01*\"4/admin/environments/{environment_id}/snapshot/create\x12\xb8\x01\n" +
	"\x17PreviewCreatingSnapshot\x12%.kirby.admin.v1.ConfigSnapshotRequest\x1a,.kirby.admin.v1.PreviewCreatingSnapshotReply\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/admin/environments/{environment_id}/snapshot/previewCreating\x12\x8c\x01\n" +
	"\x0eDeleteSnapshot\x12!.kirby.admin.v1.SnapshotIDRequest\x1a\x16.google.protobuf.Empty\"?\x82\xd3\xe4\x93\x029:\x01*\"4/admin/environments/{environment_id}/snapshot/delete\x12\x90\x01\n" +
	"\vGetSnapshot\x12!.kirby.admin.v1.SnapshotIDRequest\x1a\x1d.kirby.admin.v1.SnapshotReply\"?\x82\xd3\xe4\x93\x029:\x01*\"4/admin/environments/{environment_id}/snapshot/detail\x12\x91\x01\n" +
	"\fLoadSnapshot\x12#.kirby.admin.v1.LoadSnapshotRequest\x1a\x1d.kirby.admin.v1.SnapshotReply\"=\x82\xd3\xe4\x93\x027:\x01*\"2/admin/environments/{environment_id}/snapshot/load\x12\x99\x01\n" +
	"\x0fCurrentSnapshot\x12%.kirby.admin.v1.ConfigSnapshotRequest\x1a\x1d.kirby.admin.v1.SnapshotReply\"@\x82\xd3\xe4\x93\x02::\x01*\"5/admin/environments/{environment_id}/snapshot/current\x12\x9b\x01\n" +
	"\x10ReleasedSnapshot\x12%.kirby.admin.v1.ConfigSnapshotRequest\x1a\x1d.kirby.admin.v1.SnapshotReply\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/admin/environments/{environment_id}/snapshot/released\x12\x95\x01\n" +
	"\fListSnapshot\x12#.kirby.admin.v1.ListSnapshotRequest\x1a!.kirby.admin.v1.ListSnapshotReply\"=\x82\xd3\xe4\x93\x027:\x01*\"2/admin/environments/{environment_id}/snapshot/listB2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_snapshot_proto_rawDescOnce sync.Once
	file_admin_snapshot_proto_rawDescData []byte
)

func file_admin_snapshot_proto_rawDescGZIP() []byte {
	file_admin_snapshot_proto_rawDescOnce.Do(func() {
		file_admin_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_snapshot_proto_rawDesc), len(file_admin_snapshot_proto_rawDesc)))
	})
	return file_admin_snapshot_proto_rawDescData
}

var file_admin_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_admin_snapshot_proto_goTypes = []any{
	(*SnapshotIDRequest)(nil),            // 0: kirby.admin.v1.SnapshotIDRequest
	(*ConfigSnapshotRequest)(nil),        // 1: kirby.admin.v1.ConfigSnapshotRequest
	(*CreateSnapshotRequest)(nil),        // 2: kirby.admin.v1.CreateSnapshotRequest
	(*LoadSnapshotRequest)(nil),          // 3: kirby.admin.v1.LoadSnapshotRequest
	(*ListSnapshotRequest)(nil),          // 4: kirby.admin.v1.ListSnapshotRequest
	(*SnapshotReply)(nil),                // 5: kirby.admin.v1.SnapshotReply
	(*PreviewCreatingSnapshotReply)(nil), // 6: kirby.admin.v1.PreviewCreatingSnapshotReply
	(*ListSnapshotReply)(nil),            // 7: kirby.admin.v1.ListSnapshotReply
	(common.Snapshot_Tag)(0),             // 8: kirby.common.v1.Snapshot.Tag
	(*common.PaginationRequest)(nil),     // 9: kirby.common.v1.PaginationRequest
	(*common.Snapshot)(nil),              // 10: kirby.common.v1.Snapshot
	(*common.Pagination)(nil),            // 11: kirby.common.v1.Pagination
	(*common.SimpleSnapshot)(nil),        // 12: kirby.common.v1.SimpleSnapshot
	(*emptypb.Empty)(nil),                // 13: google.protobuf.Empty
}
var file_admin_snapshot_proto_depIdxs = []int32{
	8,  // 0: kirby.admin.v1.CreateSnapshotRequest.tags:type_name -> kirby.common.v1.Snapshot.Tag
	9,  // 1: kirby.admin.v1.ListSnapshotRequest.page:type_name -> kirby.common.v1.PaginationRequest
	10, // 2: kirby.admin.v1.SnapshotReply.snapshot:type_name -> kirby.common.v1.Snapshot
	11, // 3: kirby.admin.v1.ListSnapshotReply.page:type_name -> kirby.common.v1.Pagination
	12, // 4: kirby.admin.v1.ListSnapshotReply.list:type_name -> kirby.common.v1.SimpleSnapshot
	2,  // 5: kirby.admin.v1.SnapshotService.CreateSnapshot:input_type -> kirby.admin.v1.CreateSnapshotRequest
	1,  // 6: kirby.admin.v1.SnapshotService.PreviewCreatingSnapshot:input_type -> kirby.admin.v1.ConfigSnapshotRequest
	0,  // 7: kirby.admin.v1.SnapshotService.DeleteSnapshot:input_type -> kirby.admin.v1.SnapshotIDRequest
	0,  // 8: kirby.admin.v1.SnapshotService.GetSnapshot:input_type -> kirby.admin.v1.SnapshotIDRequest
	3,  // 9: kirby.admin.v1.SnapshotService.LoadSnapshot:input_type -> kirby.admin.v1.LoadSnapshotRequest
	1,  // 10: kirby.admin.v1.SnapshotService.CurrentSnapshot:input_type -> kirby.admin.v1.ConfigSnapshotRequest
	1,  // 11: kirby.admin.v1.SnapshotService.ReleasedSnapshot:input_type -> kirby.admin.v1.ConfigSnapshotRequest
	4,  // 12: kirby.admin.v1.SnapshotService.ListSnapshot:input_type -> kirby.admin.v1.ListSnapshotRequest
	5,  // 13: kirby.admin.v1.SnapshotService.CreateSnapshot:output_type -> kirby.admin.v1.SnapshotReply
	6,  // 14: kirby.admin.v1.SnapshotService.PreviewCreatingSnapshot:output_type -> kirby.admin.v1.PreviewCreatingSnapshotReply
	13, // 15: kirby.admin.v1.SnapshotService.DeleteSnapshot:output_type -> google.protobuf.Empty
	5,  // 16: kirby.admin.v1.SnapshotService.GetSnapshot:output_type -> kirby.admin.v1.SnapshotReply
	5,  // 17: kirby.admin.v1.SnapshotService.LoadSnapshot:output_type -> kirby.admin.v1.SnapshotReply
	5,  // 18: kirby.admin.v1.SnapshotService.CurrentSnapshot:output_type -> kirby.admin.v1.SnapshotReply
	5,  // 19: kirby.admin.v1.SnapshotService.ReleasedSnapshot:output_type -> kirby.admin.v1.SnapshotReply
	7,  // 20: kirby.admin.v1.SnapshotService.ListSnapshot:output_type -> kirby.admin.v1.ListSnapshotReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_admin_snapshot_proto_init() }
func file_admin_snapshot_proto_init() {
	if File_admin_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_snapshot_proto_rawDesc), len(file_admin_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_snapshot_proto_goTypes,
		DependencyIndexes: file_admin_snapshot_proto_depIdxs,
		MessageInfos:      file_admin_snapshot_proto_msgTypes,
	}.Build()
	File_admin_snapshot_proto = out.File
	file_admin_snapshot_proto_goTypes = nil
	file_admin_snapshot_proto_depIdxs = nil
}
