// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/snapshot_transfer.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSnapshotTransferServiceExportSnapshot = "/kirby.admin.v1.SnapshotTransferService/ExportSnapshot"
const OperationSnapshotTransferServiceImportSnapshot = "/kirby.admin.v1.SnapshotTransferService/ImportSnapshot"

type SnapshotTransferServiceHTTPServer interface {
	ExportSnapshot(context.Context, *ExportSnapshotRequest) (*ExportSnapshotReply, error)
	ImportSnapshot(context.Context, *ImportSnapshotRequest) (*ImportSnapshotReply, error)
}

func RegisterSnapshotTransferServiceHTTPServer(s *http.Server, srv SnapshotTransferServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/admin/environments/{source_environment_id}/snapshots/{snapshot_id}/export", _SnapshotTransferService_ExportSnapshot0_HTTP_Handler(srv))
	r.POST("/admin/environments/{target_environment_id}/snapshot-imports", _SnapshotTransferService_ImportSnapshot0_HTTP_Handler(srv))
}

func _SnapshotTransferService_ExportSnapshot0_HTTP_Handler(srv SnapshotTransferServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportSnapshotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotTransferServiceExportSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportSnapshot(ctx, req.(*ExportSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportSnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _SnapshotTransferService_ImportSnapshot0_HTTP_Handler(srv SnapshotTransferServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportSnapshotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSnapshotTransferServiceImportSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportSnapshot(ctx, req.(*ImportSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportSnapshotReply)
		return ctx.Result(200, reply)
	}
}

type SnapshotTransferServiceHTTPClient interface {
	ExportSnapshot(ctx context.Context, req *ExportSnapshotRequest, opts ...http.CallOption) (rsp *ExportSnapshotReply, err error)
	ImportSnapshot(ctx context.Context, req *ImportSnapshotRequest, opts ...http.CallOption) (rsp *ImportSnapshotReply, err error)
}

type SnapshotTransferServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSnapshotTransferServiceHTTPClient(client *http.Client) SnapshotTransferServiceHTTPClient {
	return &SnapshotTransferServiceHTTPClientImpl{client}
}

func (c *SnapshotTransferServiceHTTPClientImpl) ExportSnapshot(ctx context.Context, in *ExportSnapshotRequest, opts ...http.CallOption) (*ExportSnapshotReply, error) {
	var out ExportSnapshotReply
	pattern := "/admin/environments/{source_environment_id}/snapshots/{snapshot_id}/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSnapshotTransferServiceExportSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SnapshotTransferServiceHTTPClientImpl) ImportSnapshot(ctx context.Context, in *ImportSnapshotRequest, opts ...http.CallOption) (*ImportSnapshotReply, error) {
	var out ImportSnapshotReply
	pattern := "/admin/environments/{target_environment_id}/snapshot-imports"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSnapshotTransferServiceImportSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
