// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/snapshot_transfer.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportConflictStrategy int32

const (
	ImportConflictStrategy_UNSPECIFIED ImportConflictStrategy = 0
	ImportConflictStrategy_FAIL        ImportConflictStrategy = 1
	ImportConflictStrategy_REPLACE     ImportConflictStrategy = 2
)

// Enum value maps for ImportConflictStrategy.
var (
	ImportConflictStrategy_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "FAIL",
		2: "REPLACE",
	}
	ImportConflictStrategy_value = map[string]int32{
		"UNSPECIFIED": 0,
		"FAIL":        1,
		"REPLACE":     2,
	}
)

func (x ImportConflictStrategy) Enum() *ImportConflictStrategy {
	p := new(ImportConflictStrategy)
	*p = x
	return p
}

func (x ImportConflictStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportConflictStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_snapshot_transfer_proto_enumTypes[0].Descriptor()
}

func (ImportConflictStrategy) Type() protoreflect.EnumType {
	return &file_admin_snapshot_transfer_proto_enumTypes[0]
}

func (x ImportConflictStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportConflictStrategy.Descriptor instead.
func (ImportConflictStrategy) EnumDescriptor() ([]byte, []int) {
	return file_admin_snapshot_transfer_proto_rawDescGZIP(), []int{0}
}

type ExportSnapshotRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceEnvironmentId int64                  `protobuf:"varint,1,opt,name=source_environment_id,json=sourceEnvironmentId,proto3" json:"source_environment_id,omitempty"`
	SnapshotId          int64                  `protobuf:"varint,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExportSnapshotRequest) Reset() {
	*x = ExportSnapshotRequest{}
	mi := &file_admin_snapshot_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotRequest) ProtoMessage() {}

func (x *ExportSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ExportSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSnapshotRequest) GetSourceEnvironmentId() int64 {
	if x != nil {
		return x.SourceEnvironmentId
	}
	return 0
}

func (x *ExportSnapshotRequest) GetSnapshotId() int64 {
	if x != nil {
		return x.SnapshotId
	}
	return 0
}

type ExportSnapshotReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SourceEnvironmentId int64                  `protobuf:"varint,1,opt,name=source_environment_id,json=sourceEnvironmentId,proto3" json:"source_environment_id,omitempty"`
	Snapshot            *common.Snapshot       `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExportSnapshotReply) Reset() {
	*x = ExportSnapshotReply{}
	mi := &file_admin_snapshot_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotReply) ProtoMessage() {}

func (x *ExportSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotReply.ProtoReflect.Descriptor instead.
func (*ExportSnapshotReply) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ExportSnapshotReply) GetSourceEnvironmentId() int64 {
	if x != nil {
		return x.SourceEnvironmentId
	}
	return 0
}

func (x *ExportSnapshotReply) GetSnapshot() *common.Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ImportSnapshotRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetEnvironmentId int64                  `protobuf:"varint,1,opt,name=target_environment_id,json=targetEnvironmentId,proto3" json:"target_environment_id,omitempty"`
	SourceEnvironmentId int64                  `protobuf:"varint,2,opt,name=source_environment_id,json=sourceEnvironmentId,proto3" json:"source_environment_id,omitempty"`
	SourceSnapshotId    int64                  `protobuf:"varint,3,opt,name=source_snapshot_id,json=sourceSnapshotId,proto3" json:"source_snapshot_id,omitempty"`
	TargetProjectId     int64                  `protobuf:"varint,4,opt,name=target_project_id,json=targetProjectId,proto3" json:"target_project_id,omitempty"`
	TargetConfigId      *int64                 `protobuf:"varint,5,opt,name=target_config_id,json=targetConfigId,proto3,oneof" json:"target_config_id,omitempty"`
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tags                []common.Snapshot_Tag  `protobuf:"varint,7,rep,packed,name=tags,proto3,enum=kirby.common.v1.Snapshot_Tag" json:"tags,omitempty"`
	IdempotencyKey      string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// FAIL is required when creating a new target config. REPLACE is only valid
	// when target_config_id is explicitly provided; the business layer must
	// reject REPLACE without that target.
	ConflictStrategy ImportConflictStrategy `protobuf:"varint,9,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=kirby.admin.v1.ImportConflictStrategy" json:"conflict_strategy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImportSnapshotRequest) Reset() {
	*x = ImportSnapshotRequest{}
	mi := &file_admin_snapshot_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSnapshotRequest) ProtoMessage() {}

func (x *ImportSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ImportSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *ImportSnapshotRequest) GetTargetEnvironmentId() int64 {
	if x != nil {
		return x.TargetEnvironmentId
	}
	return 0
}

func (x *ImportSnapshotRequest) GetSourceEnvironmentId() int64 {
	if x != nil {
		return x.SourceEnvironmentId
	}
	return 0
}

func (x *ImportSnapshotRequest) GetSourceSnapshotId() int64 {
	if x != nil {
		return x.SourceSnapshotId
	}
	return 0
}

func (x *ImportSnapshotRequest) GetTargetProjectId() int64 {
	if x != nil {
		return x.TargetProjectId
	}
	return 0
}

func (x *ImportSnapshotRequest) GetTargetConfigId() int64 {
	if x != nil && x.TargetConfigId != nil {
		return *x.TargetConfigId
	}
	return 0
}

func (x *ImportSnapshotRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImportSnapshotRequest) GetTags() []common.Snapshot_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ImportSnapshotRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ImportSnapshotRequest) GetConflictStrategy() ImportConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ImportConflictStrategy_UNSPECIFIED
}

type ImportSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *common.Snapshot       `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Replayed      bool                   `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSnapshotReply) Reset() {
	*x = ImportSnapshotReply{}
	mi := &file_admin_snapshot_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSnapshotReply) ProtoMessage() {}

func (x *ImportSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_snapshot_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSnapshotReply.ProtoReflect.Descriptor instead.
func (*ImportSnapshotReply) Descriptor() ([]byte, []int) {
	return file_admin_snapshot_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *ImportSnapshotReply) GetSnapshot() *common.Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ImportSnapshotReply) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

var File_admin_snapshot_transfer_proto protoreflect.FileDescriptor

const file_admin_snapshot_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1dadmin/snapshot_transfer.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x13common/entity.proto\x1a\x17validate/validate.proto\"~\n" +
	"\x15ExportSnapshotRequest\x12;\n" +
	"\x15source_environment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x13sourceEnvironmentId\x12(\n" +
	"\vsnapshot_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"snapshotId\"\x80\x01\n" +
	"\x13ExportSnapshotReply\x122\n" +
	"\x15source_environment_id\x18\x01 \x01(\x03R\x13sourceEnvironmentId\x125\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x19.kirby.common.v1.SnapshotR\bsnapshot\"\xc5\x04\n" +
	"\x15ImportSnapshotRequest\x12;\n" +
	"\x15target_environment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x13targetEnvironmentId\x12;\n" +
	"\x15source_environment_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x13sourceEnvironmentId\x125\n" +
	"\x12source_snapshot_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x10sourceSnapshotId\x123\n" +
	"\x11target_project_id\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x0ftargetProjectId\x126\n" +
	"\x10target_config_id\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02 \x00H\x00R\x0etargetConfigId\x88\x01\x01\x12,\n" +
	"\vdescription\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xff\x01R\vdescription\x121\n" +
	"\x04tags\x18\a \x03(\x0e2\x1d.kirby.common.v1.Snapshot.TagR\x04tags\x123\n" +
	"\x0fidempotency_key\x18\b \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x10\x18\x80\x01R\x0eidempotencyKey\x12c\n" +
	"\x11conflict_strategy\x18\t \x01(\x0e2&.kirby.admin.v1.ImportConflictStrategyB\x0e\xe2A\x01\x02\xfaB\a\x82\x01\x04\x10\x01 \x00R\x10conflictStrategyB\x13\n" +
	"\x11_target_config_id\"h\n" +
	"\x13ImportSnapshotReply\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.kirby.common.v1.SnapshotR\bsnapshot\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed*@\n" +
	"\x16ImportConflictStrategy\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\v\n" +
	"\aREPLACE\x10\x022\xf4\x02\n" +
	"\x17SnapshotTransferService\x12\xb0\x01\n" +
	"\x0eExportSnapshot\x12%.kirby.admin.v1.ExportSnapshotRequest\x1a#.kirby.admin.v1.ExportSnapshotReply\"R\x82\xd3\xe4\x93\x02L\x12J/admin/environments/{source_environment_id}/snapshots/{snapshot_id}/export\x12\xa5\x01\n" +
	"\x0eImportSnapshot\x12%.kirby.admin.v1.ImportSnapshotRequest\x1a#.kirby.admin.v1.ImportSnapshotReply\"G\x82\xd3\xe4\x93\x02A:\x01*\"</admin/environments/{target_environment_id}/snapshot-importsB2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_snapshot_transfer_proto_rawDescOnce sync.Once
	file_admin_snapshot_transfer_proto_rawDescData []byte
)

func file_admin_snapshot_transfer_proto_rawDescGZIP() []byte {
	file_admin_snapshot_transfer_proto_rawDescOnce.Do(func() {
		file_admin_snapshot_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_snapshot_transfer_proto_rawDesc), len(file_admin_snapshot_transfer_proto_rawDesc)))
	})
	return file_admin_snapshot_transfer_proto_rawDescData
}

var file_admin_snapshot_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_snapshot_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_snapshot_transfer_proto_goTypes = []any{
	(ImportConflictStrategy)(0),   // 0: kirby.admin.v1.ImportConflictStrategy
	(*ExportSnapshotRequest)(nil), // 1: kirby.admin.v1.ExportSnapshotRequest
	(*ExportSnapshotReply)(nil),   // 2: kirby.admin.v1.ExportSnapshotReply
	(*ImportSnapshotRequest)(nil), // 3: kirby.admin.v1.ImportSnapshotRequest
	(*ImportSnapshotReply)(nil),   // 4: kirby.admin.v1.ImportSnapshotReply
	(*common.Snapshot)(nil),       // 5: kirby.common.v1.Snapshot
	(common.Snapshot_Tag)(0),      // 6: kirby.common.v1.Snapshot.Tag
}
var file_admin_snapshot_transfer_proto_depIdxs = []int32{
	5, // 0: kirby.admin.v1.ExportSnapshotReply.snapshot:type_name -> kirby.common.v1.Snapshot
	6, // 1: kirby.admin.v1.ImportSnapshotRequest.tags:type_name -> kirby.common.v1.Snapshot.Tag
	0, // 2: kirby.admin.v1.ImportSnapshotRequest.conflict_strategy:type_name -> kirby.admin.v1.ImportConflictStrategy
	5, // 3: kirby.admin.v1.ImportSnapshotReply.snapshot:type_name -> kirby.common.v1.Snapshot
	1, // 4: kirby.admin.v1.SnapshotTransferService.ExportSnapshot:input_type -> kirby.admin.v1.ExportSnapshotRequest
	3, // 5: kirby.admin.v1.SnapshotTransferService.ImportSnapshot:input_type -> kirby.admin.v1.ImportSnapshotRequest
	2, // 6: kirby.admin.v1.SnapshotTransferService.ExportSnapshot:output_type -> kirby.admin.v1.ExportSnapshotReply
	4, // 7: kirby.admin.v1.SnapshotTransferService.ImportSnapshot:output_type -> kirby.admin.v1.ImportSnapshotReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_admin_snapshot_transfer_proto_init() }
func file_admin_snapshot_transfer_proto_init() {
	if File_admin_snapshot_transfer_proto != nil {
		return
	}
	file_admin_snapshot_transfer_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_snapshot_transfer_proto_rawDesc), len(file_admin_snapshot_transfer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_snapshot_transfer_proto_goTypes,
		DependencyIndexes: file_admin_snapshot_transfer_proto_depIdxs,
		EnumInfos:         file_admin_snapshot_transfer_proto_enumTypes,
		MessageInfos:      file_admin_snapshot_transfer_proto_msgTypes,
	}.Build()
	File_admin_snapshot_transfer_proto = out.File
	file_admin_snapshot_transfer_proto_goTypes = nil
	file_admin_snapshot_transfer_proto_depIdxs = nil
}
