syntax = "proto3";

package kirby.admin.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "common/entity.proto";
import "validate/validate.proto";

option go_package = "github.com/yvvlee/kirby/server/api/admin;adminv1";

service StructureService {
  rpc CreateStructure(CreateStructureRequest) returns (StructureReply) {
    option (google.api.http) = {post: "/admin/environments/{environment_id}/structure/create", body: "*"};
  }
  rpc UpdateStructure(UpdateStructureRequest) returns (StructureReply) {
    option (google.api.http) = {post: "/admin/environments/{environment_id}/structure/update", body: "*"};
  }
  rpc ListStructure(ListStructureRequest) returns (ListStructureReply) {
    option (google.api.http) = {post: "/admin/environments/{environment_id}/structure/list", body: "*"};
  }
  rpc DeleteStructure(StructureIDRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {post: "/admin/environments/{environment_id}/structure/delete", body: "*"};
  }
}

message StructureIDRequest {
  int64 environment_id = 1 [(validate.rules).int64 = {gt: 0}];
  int64 id = 2 [(validate.rules).int64 = {gt: 0}];
}

message CreateStructureRequest {
  int64 environment_id = 1 [(validate.rules).int64 = {gt: 0}];
  int64 config_id = 2 [(validate.rules).int64 = {gt: 0}];
  string key = 3 [(validate.rules).string = {
    min_len: 1, max_len: 64, pattern: "^[A-Za-z][A-Za-z0-9]*$"
  }];
  string name = 4 [(validate.rules).string = {min_len: 1, max_len: 64}];
  string description = 5 [(validate.rules).string = {max_len: 255}];
}

message UpdateStructureRequest {
  int64 environment_id = 1 [(validate.rules).int64 = {gt: 0}];
  int64 id = 2 [(validate.rules).int64 = {gt: 0}];
  string key = 3 [(validate.rules).string = {
    min_len: 1, max_len: 64, pattern: "^[A-Za-z][A-Za-z0-9]*$"
  }];
  string name = 4 [(validate.rules).string = {min_len: 1, max_len: 64}];
  string description = 5 [(validate.rules).string = {max_len: 255}];
  repeated kirby.common.v1.Field fields = 6 [(validate.rules).repeated = {min_items: 1}];
  uint32 version = 55;
}

message ListStructureRequest {
  int64 environment_id = 1 [(validate.rules).int64 = {gt: 0}];
  int64 config_id = 2 [(validate.rules).int64 = {gt: 0}];
  int64 project_id = 3 [(validate.rules).int64 = {gt: 0}];
  optional int64 ignore_dependency_id = 4 [(validate.rules).int64 = {gt: 0}];
}

message StructureReply {
  kirby.common.v1.Structure structure = 1;
}

message ListStructureReply {
  repeated kirby.common.v1.Structure list = 1;
}
