// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.1
// source: admin/structure.proto

package adminv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStructureServiceCreateStructure = "/kirby.admin.v1.StructureService/CreateStructure"
const OperationStructureServiceDeleteStructure = "/kirby.admin.v1.StructureService/DeleteStructure"
const OperationStructureServiceListStructure = "/kirby.admin.v1.StructureService/ListStructure"
const OperationStructureServiceUpdateStructure = "/kirby.admin.v1.StructureService/UpdateStructure"

type StructureServiceHTTPServer interface {
	CreateStructure(context.Context, *CreateStructureRequest) (*StructureReply, error)
	DeleteStructure(context.Context, *StructureIDRequest) (*emptypb.Empty, error)
	ListStructure(context.Context, *ListStructureRequest) (*ListStructureReply, error)
	UpdateStructure(context.Context, *UpdateStructureRequest) (*StructureReply, error)
}

func RegisterStructureServiceHTTPServer(s *http.Server, srv StructureServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/environments/{environment_id}/structure/create", _StructureService_CreateStructure0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/structure/update", _StructureService_UpdateStructure0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/structure/list", _StructureService_ListStructure0_HTTP_Handler(srv))
	r.POST("/admin/environments/{environment_id}/structure/delete", _StructureService_DeleteStructure0_HTTP_Handler(srv))
}

func _StructureService_CreateStructure0_HTTP_Handler(srv StructureServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateStructureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStructureServiceCreateStructure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateStructure(ctx, req.(*CreateStructureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StructureReply)
		return ctx.Result(200, reply)
	}
}

func _StructureService_UpdateStructure0_HTTP_Handler(srv StructureServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStructureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStructureServiceUpdateStructure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStructure(ctx, req.(*UpdateStructureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StructureReply)
		return ctx.Result(200, reply)
	}
}

func _StructureService_ListStructure0_HTTP_Handler(srv StructureServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStructureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStructureServiceListStructure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStructure(ctx, req.(*ListStructureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStructureReply)
		return ctx.Result(200, reply)
	}
}

func _StructureService_DeleteStructure0_HTTP_Handler(srv StructureServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StructureIDRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStructureServiceDeleteStructure)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteStructure(ctx, req.(*StructureIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type StructureServiceHTTPClient interface {
	CreateStructure(ctx context.Context, req *CreateStructureRequest, opts ...http.CallOption) (rsp *StructureReply, err error)
	DeleteStructure(ctx context.Context, req *StructureIDRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListStructure(ctx context.Context, req *ListStructureRequest, opts ...http.CallOption) (rsp *ListStructureReply, err error)
	UpdateStructure(ctx context.Context, req *UpdateStructureRequest, opts ...http.CallOption) (rsp *StructureReply, err error)
}

type StructureServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStructureServiceHTTPClient(client *http.Client) StructureServiceHTTPClient {
	return &StructureServiceHTTPClientImpl{client}
}

func (c *StructureServiceHTTPClientImpl) CreateStructure(ctx context.Context, in *CreateStructureRequest, opts ...http.CallOption) (*StructureReply, error) {
	var out StructureReply
	pattern := "/admin/environments/{environment_id}/structure/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStructureServiceCreateStructure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StructureServiceHTTPClientImpl) DeleteStructure(ctx context.Context, in *StructureIDRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/admin/environments/{environment_id}/structure/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStructureServiceDeleteStructure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StructureServiceHTTPClientImpl) ListStructure(ctx context.Context, in *ListStructureRequest, opts ...http.CallOption) (*ListStructureReply, error) {
	var out ListStructureReply
	pattern := "/admin/environments/{environment_id}/structure/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStructureServiceListStructure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StructureServiceHTTPClientImpl) UpdateStructure(ctx context.Context, in *UpdateStructureRequest, opts ...http.CallOption) (*StructureReply, error) {
	var out StructureReply
	pattern := "/admin/environments/{environment_id}/structure/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStructureServiceUpdateStructure))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
