// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/structure.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StructureIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructureIDRequest) Reset() {
	*x = StructureIDRequest{}
	mi := &file_admin_structure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureIDRequest) ProtoMessage() {}

func (x *StructureIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureIDRequest.ProtoReflect.Descriptor instead.
func (*StructureIDRequest) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{0}
}

func (x *StructureIDRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *StructureIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStructureRequest) Reset() {
	*x = CreateStructureRequest{}
	mi := &file_admin_structure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStructureRequest) ProtoMessage() {}

func (x *CreateStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStructureRequest.ProtoReflect.Descriptor instead.
func (*CreateStructureRequest) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStructureRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *CreateStructureRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *CreateStructureRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateStructureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStructureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateStructureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*common.Field        `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStructureRequest) Reset() {
	*x = UpdateStructureRequest{}
	mi := &file_admin_structure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStructureRequest) ProtoMessage() {}

func (x *UpdateStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStructureRequest.ProtoReflect.Descriptor instead.
func (*UpdateStructureRequest) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStructureRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *UpdateStructureRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStructureRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateStructureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStructureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateStructureRequest) GetFields() []*common.Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateStructureRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListStructureRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId      int64                  `protobuf:"varint,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConfigId           int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ProjectId          int64                  `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IgnoreDependencyId *int64                 `protobuf:"varint,4,opt,name=ignore_dependency_id,json=ignoreDependencyId,proto3,oneof" json:"ignore_dependency_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListStructureRequest) Reset() {
	*x = ListStructureRequest{}
	mi := &file_admin_structure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStructureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStructureRequest) ProtoMessage() {}

func (x *ListStructureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStructureRequest.ProtoReflect.Descriptor instead.
func (*ListStructureRequest) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{3}
}

func (x *ListStructureRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *ListStructureRequest) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ListStructureRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListStructureRequest) GetIgnoreDependencyId() int64 {
	if x != nil && x.IgnoreDependencyId != nil {
		return *x.IgnoreDependencyId
	}
	return 0
}

type StructureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Structure     *common.Structure      `protobuf:"bytes,1,opt,name=structure,proto3" json:"structure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructureReply) Reset() {
	*x = StructureReply{}
	mi := &file_admin_structure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureReply) ProtoMessage() {}

func (x *StructureReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureReply.ProtoReflect.Descriptor instead.
func (*StructureReply) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{4}
}

func (x *StructureReply) GetStructure() *common.Structure {
	if x != nil {
		return x.Structure
	}
	return nil
}

type ListStructureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*common.Structure    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStructureReply) Reset() {
	*x = ListStructureReply{}
	mi := &file_admin_structure_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStructureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStructureReply) ProtoMessage() {}

func (x *ListStructureReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_structure_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStructureReply.ProtoReflect.Descriptor instead.
func (*ListStructureReply) Descriptor() ([]byte, []int) {
	return file_admin_structure_proto_rawDescGZIP(), []int{5}
}

func (x *ListStructureReply) GetList() []*common.Structure {
	if x != nil {
		return x.List
	}
	return nil
}

var File_admin_structure_proto protoreflect.FileDescriptor

const file_admin_structure_proto_rawDesc = "" +
	"\n" +
	"\x15admin/structure.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/entity.proto\x1a\x17validate/validate.proto\"]\n" +
	"\x12StructureIDRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"\xee\x01\n" +
	"\x16CreateStructureRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12$\n" +
	"\tconfig_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\x123\n" +
	"\x03key\x18\x03 \x01(\tB!\xfaB\x1er\x1c\x10\x01\x18@2\x16^[A-Za-z][A-Za-z0-9]*$R\x03key\x12\x1d\n" +
	"\x04name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x04name\x12*\n" +
	"\vdescription\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\vdescription\"\xb5\x02\n" +
	"\x16UpdateStructureRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12\x17\n" +
	"\x02id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x123\n" +
	"\x03key\x18\x03 \x01(\tB!\xfaB\x1er\x1c\x10\x01\x18@2\x16^[A-Za-z][A-Za-z0-9]*$R\x03key\x12\x1d\n" +
	"\x04name\x18\x04 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x04name\x12*\n" +
	"\vdescription\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x18\xff\x01R\vdescription\x128\n" +
	"\x06fields\x18\x06 \x03(\v2\x16.kirby.common.v1.FieldB\b\xfaB\x05\x92\x01\x02\b\x01R\x06fields\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\xed\x01\n" +
	"\x14ListStructureRequest\x12.\n" +
	"\x0eenvironment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\renvironmentId\x12$\n" +
	"\tconfig_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bconfigId\x12&\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tprojectId\x12>\n" +
	"\x14ignore_dependency_id\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02 \x00H\x00R\x12ignoreDependencyId\x88\x01\x01B\x17\n" +
	"\x15_ignore_dependency_id\"J\n" +
	"\x0eStructureReply\x128\n" +
	"\tstructure\x18\x01 \x01(\v2\x1a.kirby.common.v1.StructureR\tstructure\"D\n" +
	"\x12ListStructureReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.kirby.common.v1.StructureR\x04list2\xfc\x04\n" +
	"\x10StructureService\x12\x9b\x01\n" +
	"\x0fCreateStructure\x12&.kirby.admin.v1.CreateStructureRequest\x1a\x1e.kirby.admin.v1.StructureReply\"@\x82\xd3\xe4\x93\x02::\x01*\"5/admin/environments/{environment_id}/structure/create\x12\x9b\x01\n" +
	"\x0fUpdateStructure\x12&.kirby.admin.v1.UpdateStructureRequest\x1a\x1e.kirby.admin.v1.StructureReply\"@\x82\xd3\xe4\x93\x02::\x01*\"5/admin/environments/{environment_id}/structure/update\x12\x99\x01\n" +
	"\rListStructure\x12$.kirby.admin.v1.ListStructureRequest\x1a\".kirby.admin.v1.ListStructureReply\">\x82\xd3\xe4\x93\x028:\x01*\"3/admin/environments/{environment_id}/structure/list\x12\x8f\x01\n" +
	"\x0fDeleteStructure\x12\".kirby.admin.v1.StructureIDRequest\x1a\x16.google.protobuf.Empty\"@\x82\xd3\xe4\x93\x02::\x01*\"5/admin/environments/{environment_id}/structure/deleteB2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_structure_proto_rawDescOnce sync.Once
	file_admin_structure_proto_rawDescData []byte
)

func file_admin_structure_proto_rawDescGZIP() []byte {
	file_admin_structure_proto_rawDescOnce.Do(func() {
		file_admin_structure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_structure_proto_rawDesc), len(file_admin_structure_proto_rawDesc)))
	})
	return file_admin_structure_proto_rawDescData
}

var file_admin_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_structure_proto_goTypes = []any{
	(*StructureIDRequest)(nil),     // 0: kirby.admin.v1.StructureIDRequest
	(*CreateStructureRequest)(nil), // 1: kirby.admin.v1.CreateStructureRequest
	(*UpdateStructureRequest)(nil), // 2: kirby.admin.v1.UpdateStructureRequest
	(*ListStructureRequest)(nil),   // 3: kirby.admin.v1.ListStructureRequest
	(*StructureReply)(nil),         // 4: kirby.admin.v1.StructureReply
	(*ListStructureReply)(nil),     // 5: kirby.admin.v1.ListStructureReply
	(*common.Field)(nil),           // 6: kirby.common.v1.Field
	(*common.Structure)(nil),       // 7: kirby.common.v1.Structure
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_admin_structure_proto_depIdxs = []int32{
	6, // 0: kirby.admin.v1.UpdateStructureRequest.fields:type_name -> kirby.common.v1.Field
	7, // 1: kirby.admin.v1.StructureReply.structure:type_name -> kirby.common.v1.Structure
	7, // 2: kirby.admin.v1.ListStructureReply.list:type_name -> kirby.common.v1.Structure
	1, // 3: kirby.admin.v1.StructureService.CreateStructure:input_type -> kirby.admin.v1.CreateStructureRequest
	2, // 4: kirby.admin.v1.StructureService.UpdateStructure:input_type -> kirby.admin.v1.UpdateStructureRequest
	3, // 5: kirby.admin.v1.StructureService.ListStructure:input_type -> kirby.admin.v1.ListStructureRequest
	0, // 6: kirby.admin.v1.StructureService.DeleteStructure:input_type -> kirby.admin.v1.StructureIDRequest
	4, // 7: kirby.admin.v1.StructureService.CreateStructure:output_type -> kirby.admin.v1.StructureReply
	4, // 8: kirby.admin.v1.StructureService.UpdateStructure:output_type -> kirby.admin.v1.StructureReply
	5, // 9: kirby.admin.v1.StructureService.ListStructure:output_type -> kirby.admin.v1.ListStructureReply
	8, // 10: kirby.admin.v1.StructureService.DeleteStructure:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admin_structure_proto_init() }
func file_admin_structure_proto_init() {
	if File_admin_structure_proto != nil {
		return
	}
	file_admin_structure_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_structure_proto_rawDesc), len(file_admin_structure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_structure_proto_goTypes,
		DependencyIndexes: file_admin_structure_proto_depIdxs,
		MessageInfos:      file_admin_structure_proto_msgTypes,
	}.Build()
	File_admin_structure_proto = out.File
	file_admin_structure_proto_goTypes = nil
	file_admin_structure_proto_depIdxs = nil
}
