// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: admin/user.proto

package adminv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/yvvlee/kirby/server/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	IsSystemAdmin bool                   `protobuf:"varint,4,opt,name=is_system_admin,json=isSystemAdmin,proto3" json:"is_system_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetIsSystemAdmin() bool {
	if x != nil {
		return x.IsSystemAdmin
	}
	return false
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsSystemAdmin bool                   `protobuf:"varint,3,opt,name=is_system_admin,json=isSystemAdmin,proto3" json:"is_system_admin,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_admin_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetIsSystemAdmin() bool {
	if x != nil {
		return x.IsSystemAdmin
	}
	return false
}

func (x *UpdateUserRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_admin_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_admin_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateUserStatusRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *common.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReply) Reset() {
	*x = UserReply{}
	mi := &file_admin_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReply) ProtoMessage() {}

func (x *UserReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReply.ProtoReflect.Descriptor instead.
func (*UserReply) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserReply) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*common.User         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	mi := &file_admin_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_admin_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersReply) GetList() []*common.User {
	if x != nil {
		return x.List
	}
	return nil
}

var File_admin_user_proto protoreflect.FileDescriptor

const file_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x10admin/user.proto\x12\x0ekirby.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/entity.proto\x1a\x17validate/validate.proto\"\xba\x01\n" +
	"\x11CreateUserRequest\x12&\n" +
	"\busername\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\busername\x12-\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\vdisplayName\x12&\n" +
	"\bpassword\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\f\x18\x80\bR\bpassword\x12&\n" +
	"\x0fis_system_admin\x18\x04 \x01(\bR\risSystemAdmin\"\xa6\x01\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12-\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x01R\vdisplayName\x12&\n" +
	"\x0fis_system_admin\x18\x03 \x01(\bR\risSystemAdmin\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"e\n" +
	"\x19UpdateUserPasswordRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\f\x18\x80\bR\bpassword\"o\n" +
	"\x17UpdateUserStatusRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"6\n" +
	"\tUserReply\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.kirby.common.v1.UserR\x04user\";\n" +
	"\x0eListUsersReply\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.kirby.common.v1.UserR\x04list2\xc5\x04\n" +
	"\vUserService\x12Y\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x1e.kirby.admin.v1.ListUsersReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/admin/users\x12c\n" +
	"\n" +
	"CreateUser\x12!.kirby.admin.v1.CreateUserRequest\x1a\x19.kirby.admin.v1.UserReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/admin/users\x12m\n" +
	"\n" +
	"UpdateUser\x12!.kirby.admin.v1.UpdateUserRequest\x1a\x19.kirby.admin.v1.UserReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/admin/users/{user_id}\x12\x83\x01\n" +
	"\x12UpdateUserPassword\x12).kirby.admin.v1.UpdateUserPasswordRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/admin/users/{user_id}/password\x12\x80\x01\n" +
	"\x10UpdateUserStatus\x12'.kirby.admin.v1.UpdateUserStatusRequest\x1a\x19.kirby.admin.v1.UserReply\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/admin/users/{user_id}/statusB2Z0github.com/yvvlee/kirby/server/api/admin;adminv1b\x06proto3"

var (
	file_admin_user_proto_rawDescOnce sync.Once
	file_admin_user_proto_rawDescData []byte
)

func file_admin_user_proto_rawDescGZIP() []byte {
	file_admin_user_proto_rawDescOnce.Do(func() {
		file_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_user_proto_rawDesc), len(file_admin_user_proto_rawDesc)))
	})
	return file_admin_user_proto_rawDescData
}

var file_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: kirby.admin.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),         // 1: kirby.admin.v1.UpdateUserRequest
	(*UpdateUserPasswordRequest)(nil), // 2: kirby.admin.v1.UpdateUserPasswordRequest
	(*UpdateUserStatusRequest)(nil),   // 3: kirby.admin.v1.UpdateUserStatusRequest
	(*UserReply)(nil),                 // 4: kirby.admin.v1.UserReply
	(*ListUsersReply)(nil),            // 5: kirby.admin.v1.ListUsersReply
	(*common.User)(nil),               // 6: kirby.common.v1.User
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_admin_user_proto_depIdxs = []int32{
	6, // 0: kirby.admin.v1.UserReply.user:type_name -> kirby.common.v1.User
	6, // 1: kirby.admin.v1.ListUsersReply.list:type_name -> kirby.common.v1.User
	7, // 2: kirby.admin.v1.UserService.ListUsers:input_type -> google.protobuf.Empty
	0, // 3: kirby.admin.v1.UserService.CreateUser:input_type -> kirby.admin.v1.CreateUserRequest
	1, // 4: kirby.admin.v1.UserService.UpdateUser:input_type -> kirby.admin.v1.UpdateUserRequest
	2, // 5: kirby.admin.v1.UserService.UpdateUserPassword:input_type -> kirby.admin.v1.UpdateUserPasswordRequest
	3, // 6: kirby.admin.v1.UserService.UpdateUserStatus:input_type -> kirby.admin.v1.UpdateUserStatusRequest
	5, // 7: kirby.admin.v1.UserService.ListUsers:output_type -> kirby.admin.v1.ListUsersReply
	4, // 8: kirby.admin.v1.UserService.CreateUser:output_type -> kirby.admin.v1.UserReply
	4, // 9: kirby.admin.v1.UserService.UpdateUser:output_type -> kirby.admin.v1.UserReply
	7, // 10: kirby.admin.v1.UserService.UpdateUserPassword:output_type -> google.protobuf.Empty
	4, // 11: kirby.admin.v1.UserService.UpdateUserStatus:output_type -> kirby.admin.v1.UserReply
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_admin_user_proto_init() }
func file_admin_user_proto_init() {
	if File_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_user_proto_rawDesc), len(file_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_user_proto_goTypes,
		DependencyIndexes: file_admin_user_proto_depIdxs,
		MessageInfos:      file_admin_user_proto_msgTypes,
	}.Build()
	File_admin_user_proto = out.File
	file_admin_user_proto_goTypes = nil
	file_admin_user_proto_depIdxs = nil
}
