// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/yvvlee/kirby/server/internal/config"
	"github.com/yvvlee/kirby/server/internal/provider"
	"log/slog"
)

// Injectors from wire.go:

func Initialize(contextContext context.Context, configConfig *config.Config, logger *slog.Logger) (*provider.Application, error) {
	application, err := provider.NewApplication(contextContext, configConfig, logger)
	if err != nil {
		return nil, err
	}
	return application, nil
}
