// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: errors.proto

package errorsv1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_Unknown           Error = 0
	Error_DatabaseError     Error = 2
	Error_Unimplemented     Error = 3
	Error_NoneRecordUpdated Error = 4
	Error_InvalidParam      Error = 5
	Error_Internal          Error = 6
	Error_InvalidOperation  Error = 7
	Error_BadRequest        Error = 400
	Error_Unauthorized      Error = 401
	Error_Forbidden         Error = 403
	Error_NotFound          Error = 404
	Error_Conflict          Error = 409
	Error_TooManyRequests   Error = 429
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:   "Unknown",
		2:   "DatabaseError",
		3:   "Unimplemented",
		4:   "NoneRecordUpdated",
		5:   "InvalidParam",
		6:   "Internal",
		7:   "InvalidOperation",
		400: "BadRequest",
		401: "Unauthorized",
		403: "Forbidden",
		404: "NotFound",
		409: "Conflict",
		429: "TooManyRequests",
	}
	Error_value = map[string]int32{
		"Unknown":           0,
		"DatabaseError":     2,
		"Unimplemented":     3,
		"NoneRecordUpdated": 4,
		"InvalidParam":      5,
		"Internal":          6,
		"InvalidOperation":  7,
		"BadRequest":        400,
		"Unauthorized":      401,
		"Forbidden":         403,
		"NotFound":          404,
		"Conflict":          409,
		"TooManyRequests":   429,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x0fkirby.errors.v1\x1a\x13errors/errors.proto*\xc3\x02\n" +
	"\x05Error\x12\x11\n" +
	"\aUnknown\x10\x00\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\rDatabaseError\x10\x02\x1a\x04\xa8E\xf4\x03\x12\x17\n" +
	"\rUnimplemented\x10\x03\x1a\x04\xa8E\xf5\x03\x12\x1b\n" +
	"\x11NoneRecordUpdated\x10\x04\x1a\x04\xa8E\x99\x03\x12\x16\n" +
	"\fInvalidParam\x10\x05\x1a\x04\xa8E\x90\x03\x12\x12\n" +
	"\bInternal\x10\x06\x1a\x04\xa8E\xf4\x03\x12\x1a\n" +
	"\x10InvalidOperation\x10\a\x1a\x04\xa8E\x99\x03\x12\x15\n" +
	"\n" +
	"BadRequest\x10\x90\x03\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\fUnauthorized\x10\x91\x03\x1a\x04\xa8E\x91\x03\x12\x14\n" +
	"\tForbidden\x10\x93\x03\x1a\x04\xa8E\x93\x03\x12\x13\n" +
	"\bNotFound\x10\x94\x03\x1a\x04\xa8E\x94\x03\x12\x13\n" +
	"\bConflict\x10\x99\x03\x1a\x04\xa8E\x99\x03\x12\x1a\n" +
	"\x0fTooManyRequests\x10\xad\x03\x1a\x04\xa8E\xad\x03\x1a\x04\xa0E\xf4\x03B4Z2github.com/yvvlee/kirby/server/api/errors;errorsv1b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(Error)(0), // 0: kirby.errors.v1.Error
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
