// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common/annotation.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumMeta) Reset() {
	*x = EnumMeta{}
	mi := &file_common_annotation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumMeta) ProtoMessage() {}

func (x *EnumMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_annotation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumMeta.ProtoReflect.Descriptor instead.
func (*EnumMeta) Descriptor() ([]byte, []int) {
	return file_common_annotation_proto_rawDescGZIP(), []int{0}
}

func (x *EnumMeta) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EnumMeta) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type EnumValueMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ignore        *bool                  `protobuf:"varint,1,opt,name=ignore,proto3,oneof" json:"ignore,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueMeta) Reset() {
	*x = EnumValueMeta{}
	mi := &file_common_annotation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueMeta) ProtoMessage() {}

func (x *EnumValueMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_annotation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueMeta.ProtoReflect.Descriptor instead.
func (*EnumValueMeta) Descriptor() ([]byte, []int) {
	return file_common_annotation_proto_rawDescGZIP(), []int{1}
}

func (x *EnumValueMeta) GetIgnore() bool {
	if x != nil && x.Ignore != nil {
		return *x.Ignore
	}
	return false
}

func (x *EnumValueMeta) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EnumValueMeta) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var file_common_annotation_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumMeta)(nil),
		Field:         92023,
		Name:          "kirby.common.v1.enum_meta",
		Tag:           "bytes,92023,opt,name=enum_meta",
		Filename:      "common/annotation.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueMeta)(nil),
		Field:         92023,
		Name:          "kirby.common.v1.enum_value_meta",
		Tag:           "bytes,92023,opt,name=enum_value_meta",
		Filename:      "common/annotation.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional kirby.common.v1.EnumMeta enum_meta = 92023;
	E_EnumMeta = &file_common_annotation_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional kirby.common.v1.EnumValueMeta enum_value_meta = 92023;
	E_EnumValueMeta = &file_common_annotation_proto_extTypes[1]
)

var File_common_annotation_proto protoreflect.FileDescriptor

const file_common_annotation_proto_rawDesc = "" +
	"\n" +
	"\x17common/annotation.proto\x12\x0fkirby.common.v1\x1a google/protobuf/descriptor.proto\"c\n" +
	"\bEnumMeta\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"\x90\x01\n" +
	"\rEnumValueMeta\x12\x1b\n" +
	"\x06ignore\x18\x01 \x01(\bH\x00R\x06ignore\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01B\t\n" +
	"\a_ignoreB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description:Y\n" +
	"\tenum_meta\x12\x1c.google.protobuf.EnumOptions\x18\xf7\xce\x05 \x01(\v2\x19.kirby.common.v1.EnumMetaR\benumMeta\x88\x01\x01:n\n" +
	"\x0fenum_value_meta\x12!.google.protobuf.EnumValueOptions\x18\xf7\xce\x05 \x01(\v2\x1e.kirby.common.v1.EnumValueMetaR\renumValueMeta\x88\x01\x01B4Z2github.com/yvvlee/kirby/server/api/common;commonv1b\x06proto3"

var (
	file_common_annotation_proto_rawDescOnce sync.Once
	file_common_annotation_proto_rawDescData []byte
)

func file_common_annotation_proto_rawDescGZIP() []byte {
	file_common_annotation_proto_rawDescOnce.Do(func() {
		file_common_annotation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_annotation_proto_rawDesc), len(file_common_annotation_proto_rawDesc)))
	})
	return file_common_annotation_proto_rawDescData
}

var file_common_annotation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_annotation_proto_goTypes = []any{
	(*EnumMeta)(nil),                      // 0: kirby.common.v1.EnumMeta
	(*EnumValueMeta)(nil),                 // 1: kirby.common.v1.EnumValueMeta
	(*descriptorpb.EnumOptions)(nil),      // 2: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_common_annotation_proto_depIdxs = []int32{
	2, // 0: kirby.common.v1.enum_meta:extendee -> google.protobuf.EnumOptions
	3, // 1: kirby.common.v1.enum_value_meta:extendee -> google.protobuf.EnumValueOptions
	0, // 2: kirby.common.v1.enum_meta:type_name -> kirby.common.v1.EnumMeta
	1, // 3: kirby.common.v1.enum_value_meta:type_name -> kirby.common.v1.EnumValueMeta
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_annotation_proto_init() }
func file_common_annotation_proto_init() {
	if File_common_annotation_proto != nil {
		return
	}
	file_common_annotation_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_annotation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_annotation_proto_rawDesc), len(file_common_annotation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_common_annotation_proto_goTypes,
		DependencyIndexes: file_common_annotation_proto_depIdxs,
		MessageInfos:      file_common_annotation_proto_msgTypes,
		ExtensionInfos:    file_common_annotation_proto_extTypes,
	}.Build()
	File_common_annotation_proto = out.File
	file_common_annotation_proto_goTypes = nil
	file_common_annotation_proto_depIdxs = nil
}
