// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/annotation.proto

package commonv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EnumMeta with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EnumMeta) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnumMeta with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EnumMetaMultiError, or nil
// if none found.
func (m *EnumMeta) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumMeta) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return EnumMetaMultiError(errors)
	}

	return nil
}

// EnumMetaMultiError is an error wrapping multiple validation errors returned
// by EnumMeta.ValidateAll() if the designated constraints aren't met.
type EnumMetaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnumMetaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnumMetaMultiError) AllErrors() []error { return m }

// EnumMetaValidationError is the validation error returned by
// EnumMeta.Validate if the designated constraints aren't met.
type EnumMetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnumMetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnumMetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnumMetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnumMetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnumMetaValidationError) ErrorName() string { return "EnumMetaValidationError" }

// Error satisfies the builtin error interface
func (e EnumMetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnumMeta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnumMetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnumMetaValidationError{}

// Validate checks the field values on EnumValueMeta with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EnumValueMeta) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EnumValueMeta with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EnumValueMetaMultiError, or
// nil if none found.
func (m *EnumValueMeta) ValidateAll() error {
	return m.validate(true)
}

func (m *EnumValueMeta) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Ignore != nil {
		// no validation rules for Ignore
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if len(errors) > 0 {
		return EnumValueMetaMultiError(errors)
	}

	return nil
}

// EnumValueMetaMultiError is an error wrapping multiple validation errors
// returned by EnumValueMeta.ValidateAll() if the designated constraints
// aren't met.
type EnumValueMetaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EnumValueMetaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EnumValueMetaMultiError) AllErrors() []error { return m }

// EnumValueMetaValidationError is the validation error returned by
// EnumValueMeta.Validate if the designated constraints aren't met.
type EnumValueMetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EnumValueMetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EnumValueMetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EnumValueMetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EnumValueMetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EnumValueMetaValidationError) ErrorName() string { return "EnumValueMetaValidationError" }

// Error satisfies the builtin error interface
func (e EnumValueMetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEnumValueMeta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EnumValueMetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EnumValueMetaValidationError{}
