// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common/entity.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field_BaseType int32

const (
	Field_BASE_TYPE_UNSPECIFIED Field_BaseType = 0
	Field_STRING                Field_BaseType = 1
	Field_INT                   Field_BaseType = 2
	Field_DECIMAL               Field_BaseType = 3
	Field_BOOLEAN               Field_BaseType = 4
	Field_TIME                  Field_BaseType = 5
	Field_DATE                  Field_BaseType = 6
	Field_DATETIME              Field_BaseType = 7
	Field_TIME_RANGE            Field_BaseType = 8
	Field_DATE_RANGE            Field_BaseType = 9
	Field_DATETIME_RANGE        Field_BaseType = 10
	Field_IMAGE                 Field_BaseType = 11
	Field_VIDEO                 Field_BaseType = 12
	Field_FILE                  Field_BaseType = 13
)

// Enum value maps for Field_BaseType.
var (
	Field_BaseType_name = map[int32]string{
		0:  "BASE_TYPE_UNSPECIFIED",
		1:  "STRING",
		2:  "INT",
		3:  "DECIMAL",
		4:  "BOOLEAN",
		5:  "TIME",
		6:  "DATE",
		7:  "DATETIME",
		8:  "TIME_RANGE",
		9:  "DATE_RANGE",
		10: "DATETIME_RANGE",
		11: "IMAGE",
		12: "VIDEO",
		13: "FILE",
	}
	Field_BaseType_value = map[string]int32{
		"BASE_TYPE_UNSPECIFIED": 0,
		"STRING":                1,
		"INT":                   2,
		"DECIMAL":               3,
		"BOOLEAN":               4,
		"TIME":                  5,
		"DATE":                  6,
		"DATETIME":              7,
		"TIME_RANGE":            8,
		"DATE_RANGE":            9,
		"DATETIME_RANGE":        10,
		"IMAGE":                 11,
		"VIDEO":                 12,
		"FILE":                  13,
	}
)

func (x Field_BaseType) Enum() *Field_BaseType {
	p := new(Field_BaseType)
	*p = x
	return p
}

func (x Field_BaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_BaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_entity_proto_enumTypes[0].Descriptor()
}

func (Field_BaseType) Type() protoreflect.EnumType {
	return &file_common_entity_proto_enumTypes[0]
}

func (x Field_BaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_BaseType.Descriptor instead.
func (Field_BaseType) EnumDescriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{9, 0}
}

type Snapshot_Status int32

const (
	Snapshot_STATUS_UNSPECIFIED Snapshot_Status = 0
	Snapshot_UNRELEASED         Snapshot_Status = 1
	Snapshot_RELEASED           Snapshot_Status = 3
)

// Enum value maps for Snapshot_Status.
var (
	Snapshot_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "UNRELEASED",
		3: "RELEASED",
	}
	Snapshot_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"UNRELEASED":         1,
		"RELEASED":           3,
	}
)

func (x Snapshot_Status) Enum() *Snapshot_Status {
	p := new(Snapshot_Status)
	*p = x
	return p
}

func (x Snapshot_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Snapshot_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_entity_proto_enumTypes[1].Descriptor()
}

func (Snapshot_Status) Type() protoreflect.EnumType {
	return &file_common_entity_proto_enumTypes[1]
}

func (x Snapshot_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Snapshot_Status.Descriptor instead.
func (Snapshot_Status) EnumDescriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{11, 0}
}

type Snapshot_Tag int32

const (
	Snapshot_TAG_UNSPECIFIED Snapshot_Tag = 0
	Snapshot_RELEASE         Snapshot_Tag = 1
	Snapshot_HOTFIX          Snapshot_Tag = 2
	Snapshot_REVIEW          Snapshot_Tag = 3
	Snapshot_DEBUG           Snapshot_Tag = 4
	Snapshot_DEMO            Snapshot_Tag = 5
	Snapshot_REUSE           Snapshot_Tag = 6
)

// Enum value maps for Snapshot_Tag.
var (
	Snapshot_Tag_name = map[int32]string{
		0: "TAG_UNSPECIFIED",
		1: "RELEASE",
		2: "HOTFIX",
		3: "REVIEW",
		4: "DEBUG",
		5: "DEMO",
		6: "REUSE",
	}
	Snapshot_Tag_value = map[string]int32{
		"TAG_UNSPECIFIED": 0,
		"RELEASE":         1,
		"HOTFIX":          2,
		"REVIEW":          3,
		"DEBUG":           4,
		"DEMO":            5,
		"REUSE":           6,
	}
)

func (x Snapshot_Tag) Enum() *Snapshot_Tag {
	p := new(Snapshot_Tag)
	*p = x
	return p
}

func (x Snapshot_Tag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Snapshot_Tag) Descriptor() protoreflect.EnumDescriptor {
	return file_common_entity_proto_enumTypes[2].Descriptor()
}

func (Snapshot_Tag) Type() protoreflect.EnumType {
	return &file_common_entity_proto_enumTypes[2]
}

func (x Snapshot_Tag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Snapshot_Tag.Descriptor instead.
func (Snapshot_Tag) EnumDescriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{11, 1}
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,51,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,52,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_common_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Environment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Environment) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Environment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Environment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Environment) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IsSystemAdmin bool                   `protobuf:"varint,5,opt,name=is_system_admin,json=isSystemAdmin,proto3" json:"is_system_admin,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,51,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,52,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetIsSystemAdmin() bool {
	if x != nil {
		return x.IsSystemAdmin
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Builtin       bool                   `protobuf:"varint,5,opt,name=builtin,proto3" json:"builtin,omitempty"`
	Permissions   []*Permission          `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,51,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,52,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_common_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

func (x *Role) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Role) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Role) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Role) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_common_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{3}
}

func (x *Permission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EnvironmentMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []*Role                `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentMember) Reset() {
	*x = EnvironmentMember{}
	mi := &file_common_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentMember) ProtoMessage() {}

func (x *EnvironmentMember) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentMember.ProtoReflect.Descriptor instead.
func (*EnvironmentMember) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{4}
}

func (x *EnvironmentMember) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *EnvironmentMember) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnvironmentId int64                  `protobuf:"varint,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_common_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *Project) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Project) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Project) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId      int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Key            string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsArray        bool                   `protobuf:"varint,5,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	Type           *Field_Type            `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Value          string                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	RuntimeVersion uint64                 `protobuf:"varint,8,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version        uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_common_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{6}
}

func (x *Config) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Config) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Config) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Config) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Config) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

func (x *Config) GetType() *Field_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Config) GetRuntimeVersion() uint64 {
	if x != nil {
		return x.RuntimeVersion
	}
	return 0
}

func (x *Config) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Config) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Config) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Config) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Config) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ConfigEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Values        []*SelectOption        `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEnum) Reset() {
	*x = ConfigEnum{}
	mi := &file_common_entity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEnum) ProtoMessage() {}

func (x *ConfigEnum) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEnum.ProtoReflect.Descriptor instead.
func (*ConfigEnum) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigEnum) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigEnum) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ConfigEnum) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEnum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigEnum) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigEnum) GetValues() []*SelectOption {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ConfigEnum) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ConfigEnum) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *ConfigEnum) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConfigEnum) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ConfigEnum) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Structure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*Field               `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Structure) Reset() {
	*x = Structure{}
	mi := &file_common_entity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Structure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Structure) ProtoMessage() {}

func (x *Structure) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Structure.ProtoReflect.Descriptor instead.
func (*Structure) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{8}
}

func (x *Structure) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Structure) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Structure) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Structure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Structure) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Structure) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Structure) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Structure) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Structure) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Structure) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Structure) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsArray       bool                   `protobuf:"varint,4,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	Type          *Field_Type            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_common_entity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{9}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Field) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

func (x *Field) GetType() *Field_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Field                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Children      []*TreeNode            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_common_entity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{10}
}

func (x *TreeNode) GetValue() *Field {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,4,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        Snapshot_Status        `protobuf:"varint,7,opt,name=status,proto3,enum=kirby.common.v1.Snapshot_Status" json:"status,omitempty"`
	Tags          []Snapshot_Tag         `protobuf:"varint,8,rep,packed,name=tags,proto3,enum=kirby.common.v1.Snapshot_Tag" json:"tags,omitempty"`
	IsUsing       bool                   `protobuf:"varint,9,opt,name=is_using,json=isUsing,proto3" json:"is_using,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_common_entity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{11}
}

func (x *Snapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Snapshot) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Snapshot) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Snapshot) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *Snapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Snapshot) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Snapshot) GetStatus() Snapshot_Status {
	if x != nil {
		return x.Status
	}
	return Snapshot_STATUS_UNSPECIFIED
}

func (x *Snapshot) GetTags() []Snapshot_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Snapshot) GetIsUsing() bool {
	if x != nil {
		return x.IsUsing
	}
	return false
}

func (x *Snapshot) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Snapshot) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Snapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Snapshot) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SimpleSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ConfigId      int64                  `protobuf:"varint,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,4,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        Snapshot_Status        `protobuf:"varint,6,opt,name=status,proto3,enum=kirby.common.v1.Snapshot_Status" json:"status,omitempty"`
	Tags          []Snapshot_Tag         `protobuf:"varint,7,rep,packed,name=tags,proto3,enum=kirby.common.v1.Snapshot_Tag" json:"tags,omitempty"`
	IsUsing       bool                   `protobuf:"varint,8,opt,name=is_using,json=isUsing,proto3" json:"is_using,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,51,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,52,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,53,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,54,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       uint32                 `protobuf:"varint,55,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleSnapshot) Reset() {
	*x = SimpleSnapshot{}
	mi := &file_common_entity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleSnapshot) ProtoMessage() {}

func (x *SimpleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleSnapshot.ProtoReflect.Descriptor instead.
func (*SimpleSnapshot) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{12}
}

func (x *SimpleSnapshot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleSnapshot) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SimpleSnapshot) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *SimpleSnapshot) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *SimpleSnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SimpleSnapshot) GetStatus() Snapshot_Status {
	if x != nil {
		return x.Status
	}
	return Snapshot_STATUS_UNSPECIFIED
}

func (x *SimpleSnapshot) GetTags() []Snapshot_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SimpleSnapshot) GetIsUsing() bool {
	if x != nil {
		return x.IsUsing
	}
	return false
}

func (x *SimpleSnapshot) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *SimpleSnapshot) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *SimpleSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SimpleSnapshot) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SimpleSnapshot) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ProjectApiKey struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicId   string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy  string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt  string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt *string                `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	RevokedAt  *string                `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3,oneof" json:"revoked_at,omitempty"`
	// Only the trailing characters are stored and returned for identification.
	// This value is not the secret and cannot be used to authenticate.
	SecretSuffix  string `protobuf:"bytes,8,opt,name=secret_suffix,json=secretSuffix,proto3" json:"secret_suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectApiKey) Reset() {
	*x = ProjectApiKey{}
	mi := &file_common_entity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectApiKey) ProtoMessage() {}

func (x *ProjectApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectApiKey.ProtoReflect.Descriptor instead.
func (*ProjectApiKey) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectApiKey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectApiKey) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *ProjectApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectApiKey) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ProjectApiKey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProjectApiKey) GetLastUsedAt() string {
	if x != nil && x.LastUsedAt != nil {
		return *x.LastUsedAt
	}
	return ""
}

func (x *ProjectApiKey) GetRevokedAt() string {
	if x != nil && x.RevokedAt != nil {
		return *x.RevokedAt
	}
	return ""
}

func (x *ProjectApiKey) GetSecretSuffix() string {
	if x != nil {
		return x.SecretSuffix
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectKey     string                 `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_common_entity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{14}
}

func (x *Asset) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *Asset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Asset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Asset) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Field_Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Field_Type_BaseType
	//	*Field_Type_StructureKey
	//	*Field_Type_EnumKey
	Kind          isField_Type_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field_Type) Reset() {
	*x = Field_Type{}
	mi := &file_common_entity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field_Type) ProtoMessage() {}

func (x *Field_Type) ProtoReflect() protoreflect.Message {
	mi := &file_common_entity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field_Type.ProtoReflect.Descriptor instead.
func (*Field_Type) Descriptor() ([]byte, []int) {
	return file_common_entity_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Field_Type) GetKind() isField_Type_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Field_Type) GetBaseType() Field_BaseType {
	if x != nil {
		if x, ok := x.Kind.(*Field_Type_BaseType); ok {
			return x.BaseType
		}
	}
	return Field_BASE_TYPE_UNSPECIFIED
}

func (x *Field_Type) GetStructureKey() string {
	if x != nil {
		if x, ok := x.Kind.(*Field_Type_StructureKey); ok {
			return x.StructureKey
		}
	}
	return ""
}

func (x *Field_Type) GetEnumKey() string {
	if x != nil {
		if x, ok := x.Kind.(*Field_Type_EnumKey); ok {
			return x.EnumKey
		}
	}
	return ""
}

type isField_Type_Kind interface {
	isField_Type_Kind()
}

type Field_Type_BaseType struct {
	BaseType Field_BaseType `protobuf:"varint,1,opt,name=base_type,json=baseType,proto3,enum=kirby.common.v1.Field_BaseType,oneof"`
}

type Field_Type_StructureKey struct {
	StructureKey string `protobuf:"bytes,2,opt,name=structure_key,json=structureKey,proto3,oneof"`
}

type Field_Type_EnumKey struct {
	EnumKey string `protobuf:"bytes,3,opt,name=enum_key,json=enumKey,proto3,oneof"`
}

func (*Field_Type_BaseType) isField_Type_Kind() {}

func (*Field_Type_StructureKey) isField_Type_Kind() {}

func (*Field_Type_EnumKey) isField_Type_Kind() {}

var File_common_entity_proto protoreflect.FileDescriptor

const file_common_entity_proto_rawDesc = "" +
	"\n" +
	"\x13common/entity.proto\x12\x0fkirby.common.v1\x1a\x17common/annotation.proto\x1a\x12common/types.proto\"\xd7\x01\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x183 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x184 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\xef\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12&\n" +
	"\x0fis_system_admin\x18\x05 \x01(\bR\risSystemAdmin\x12\x1d\n" +
	"\n" +
	"created_at\x183 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x184 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\x8f\x02\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\abuiltin\x18\x05 \x01(\bR\abuiltin\x12=\n" +
	"\vpermissions\x18\x06 \x03(\v2\x1b.kirby.common.v1.PermissionR\vpermissions\x12\x1d\n" +
	"\n" +
	"created_at\x183 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x184 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"d\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"k\n" +
	"\x11EnvironmentMember\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.kirby.common.v1.UserR\x04user\x12+\n" +
	"\x05roles\x18\x02 \x03(\v2\x15.kirby.common.v1.RoleR\x05roles\"\x9e\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\x03R\renvironmentId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\x8c\x03\n" +
	"\x06Config\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bis_array\x18\x05 \x01(\bR\aisArray\x12/\n" +
	"\x04type\x18\x06 \x01(\v2\x1b.kirby.common.v1.Field.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12'\n" +
	"\x0fruntime_version\x18\b \x01(\x04R\x0eruntimeVersion\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\xce\x02\n" +
	"\n" +
	"ConfigEnum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x03R\bconfigId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x125\n" +
	"\x06values\x18\x06 \x03(\v2\x1d.kirby.common.v1.SelectOptionR\x06values\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\xc6\x02\n" +
	"\tStructure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x03R\bconfigId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12.\n" +
	"\x06fields\x18\x06 \x03(\v2\x16.kirby.common.v1.FieldR\x06fields\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\xf9\x05\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bis_array\x18\x04 \x01(\bR\aisArray\x12/\n" +
	"\x04type\x18\x05 \x01(\v2\x1b.kirby.common.v1.Field.TypeR\x04type\x1a\x92\x01\n" +
	"\x04Type\x12>\n" +
	"\tbase_type\x18\x01 \x01(\x0e2\x1f.kirby.common.v1.Field.BaseTypeH\x00R\bbaseType\x12%\n" +
	"\rstructure_key\x18\x02 \x01(\tH\x00R\fstructureKey\x12\x1b\n" +
	"\benum_key\x18\x03 \x01(\tH\x00R\aenumKeyB\x06\n" +
	"\x04kind\"\xc6\x03\n" +
	"\bBaseType\x12!\n" +
	"\x15BASE_TYPE_UNSPECIFIED\x10\x00\x1a\x06\xba\xf7,\x02\b\x01\x12\x1b\n" +
	"\x06STRING\x10\x01\x1a\x0f\xba\xf7,\v\x12\t字符串\x12\x15\n" +
	"\x03INT\x10\x02\x1a\f\xba\xf7,\b\x12\x06整数\x12\x19\n" +
	"\aDECIMAL\x10\x03\x1a\f\xba\xf7,\b\x12\x06小数\x12\x1c\n" +
	"\aBOOLEAN\x10\x04\x1a\x0f\xba\xf7,\v\x12\t布尔值\x12\x16\n" +
	"\x04TIME\x10\x05\x1a\f\xba\xf7,\b\x12\x06时间\x12\x16\n" +
	"\x04DATE\x10\x06\x1a\f\xba\xf7,\b\x12\x06日期\x12 \n" +
	"\bDATETIME\x10\a\x1a\x12\xba\xf7,\x0e\x12\f日期时间\x12\"\n" +
	"\n" +
	"TIME_RANGE\x10\b\x1a\x12\xba\xf7,\x0e\x12\f时间范围\x12\"\n" +
	"\n" +
	"DATE_RANGE\x10\t\x1a\x12\xba\xf7,\x0e\x12\f日期范围\x12,\n" +
	"\x0eDATETIME_RANGE\x10\n" +
	"\x1a\x18\xba\xf7,\x14\x12\x12日期时间范围\x12\x17\n" +
	"\x05IMAGE\x10\v\x1a\f\xba\xf7,\b\x12\x06图片\x12\x17\n" +
	"\x05VIDEO\x10\f\x1a\f\xba\xf7,\b\x12\x06视频\x12\x16\n" +
	"\x04FILE\x10\r\x1a\f\xba\xf7,\b\x12\x06文件\x1a\x18\xba\xf7,\x14\n" +
	"\x12字段基础类型\"o\n" +
	"\bTreeNode\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.kirby.common.v1.FieldR\x05value\x125\n" +
	"\bchildren\x18\x02 \x03(\v2\x19.kirby.common.v1.TreeNodeR\bchildren\"\xa3\x06\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\x03R\bconfigId\x12\x1d\n" +
	"\n" +
	"config_key\x18\x04 \x01(\tR\tconfigKey\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .kirby.common.v1.Snapshot.StatusR\x06status\x121\n" +
	"\x04tags\x18\b \x03(\x0e2\x1d.kirby.common.v1.Snapshot.TagR\x04tags\x12\x19\n" +
	"\bis_using\x18\t \x01(\bR\aisUsing\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\x82\x01\n" +
	"\x06Status\x12\x1e\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x1a\x06\xba\xf7,\x02\b\x01\x12\x1f\n" +
	"\n" +
	"UNRELEASED\x10\x01\x1a\x0f\xba\xf7,\v\x12\t未发布\x12\x1d\n" +
	"\bRELEASED\x10\x03\x1a\x0f\xba\xf7,\v\x12\t已发布\x1a\x12\xba\xf7,\x0e\n" +
	"\f快照状态\"\x04\b\x02\x10\x02\"\xcc\x01\n" +
	"\x03Tag\x12\x1b\n" +
	"\x0fTAG_UNSPECIFIED\x10\x00\x1a\x06\xba\xf7,\x02\b\x01\x12\x1a\n" +
	"\aRELEASE\x10\x01\x1a\r\xba\xf7,\t\x12\aRelease\x12\x18\n" +
	"\x06HOTFIX\x10\x02\x1a\f\xba\xf7,\b\x12\x06Hotfix\x12\x18\n" +
	"\x06REVIEW\x10\x03\x1a\f\xba\xf7,\b\x12\x06Review\x12\x16\n" +
	"\x05DEBUG\x10\x04\x1a\v\xba\xf7,\a\x12\x05Debug\x12\x14\n" +
	"\x04DEMO\x10\x05\x1a\n" +
	"\xba\xf7,\x06\x12\x04Demo\x12\x16\n" +
	"\x05REUSE\x10\x06\x1a\v\xba\xf7,\a\x12\x05Reuse\x1a\x12\xba\xf7,\x0e\n" +
	"\f快照标签\"\xbb\x03\n" +
	"\x0eSimpleSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\x03R\bconfigId\x12\x1d\n" +
	"\n" +
	"config_key\x18\x04 \x01(\tR\tconfigKey\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x128\n" +
	"\x06status\x18\x06 \x01(\x0e2 .kirby.common.v1.Snapshot.StatusR\x06status\x121\n" +
	"\x04tags\x18\a \x03(\x0e2\x1d.kirby.common.v1.Snapshot.TagR\x04tags\x12\x19\n" +
	"\bis_using\x18\b \x01(\bR\aisUsing\x12\x1d\n" +
	"\n" +
	"created_by\x183 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x184 \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x185 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x186 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x187 \x01(\rR\aversion\"\x9e\x02\n" +
	"\rProjectApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12%\n" +
	"\flast_used_at\x18\x06 \x01(\tH\x00R\n" +
	"lastUsedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"revoked_at\x18\a \x01(\tH\x01R\trevokedAt\x88\x01\x01\x12#\n" +
	"\rsecret_suffix\x18\b \x01(\tR\fsecretSuffixB\x0f\n" +
	"\r_last_used_atB\r\n" +
	"\v_revoked_at\"o\n" +
	"\x05Asset\x12\x1d\n" +
	"\n" +
	"object_key\x18\x01 \x01(\tR\tobjectKey\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04sizeB4Z2github.com/yvvlee/kirby/server/api/common;commonv1b\x06proto3"

var (
	file_common_entity_proto_rawDescOnce sync.Once
	file_common_entity_proto_rawDescData []byte
)

func file_common_entity_proto_rawDescGZIP() []byte {
	file_common_entity_proto_rawDescOnce.Do(func() {
		file_common_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_entity_proto_rawDesc), len(file_common_entity_proto_rawDesc)))
	})
	return file_common_entity_proto_rawDescData
}

var file_common_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_common_entity_proto_goTypes = []any{
	(Field_BaseType)(0),       // 0: kirby.common.v1.Field.BaseType
	(Snapshot_Status)(0),      // 1: kirby.common.v1.Snapshot.Status
	(Snapshot_Tag)(0),         // 2: kirby.common.v1.Snapshot.Tag
	(*Environment)(nil),       // 3: kirby.common.v1.Environment
	(*User)(nil),              // 4: kirby.common.v1.User
	(*Role)(nil),              // 5: kirby.common.v1.Role
	(*Permission)(nil),        // 6: kirby.common.v1.Permission
	(*EnvironmentMember)(nil), // 7: kirby.common.v1.EnvironmentMember
	(*Project)(nil),           // 8: kirby.common.v1.Project
	(*Config)(nil),            // 9: kirby.common.v1.Config
	(*ConfigEnum)(nil),        // 10: kirby.common.v1.ConfigEnum
	(*Structure)(nil),         // 11: kirby.common.v1.Structure
	(*Field)(nil),             // 12: kirby.common.v1.Field
	(*TreeNode)(nil),          // 13: kirby.common.v1.TreeNode
	(*Snapshot)(nil),          // 14: kirby.common.v1.Snapshot
	(*SimpleSnapshot)(nil),    // 15: kirby.common.v1.SimpleSnapshot
	(*ProjectApiKey)(nil),     // 16: kirby.common.v1.ProjectApiKey
	(*Asset)(nil),             // 17: kirby.common.v1.Asset
	(*Field_Type)(nil),        // 18: kirby.common.v1.Field.Type
	(*SelectOption)(nil),      // 19: kirby.common.v1.SelectOption
}
var file_common_entity_proto_depIdxs = []int32{
	6,  // 0: kirby.common.v1.Role.permissions:type_name -> kirby.common.v1.Permission
	4,  // 1: kirby.common.v1.EnvironmentMember.user:type_name -> kirby.common.v1.User
	5,  // 2: kirby.common.v1.EnvironmentMember.roles:type_name -> kirby.common.v1.Role
	18, // 3: kirby.common.v1.Config.type:type_name -> kirby.common.v1.Field.Type
	19, // 4: kirby.common.v1.ConfigEnum.values:type_name -> kirby.common.v1.SelectOption
	12, // 5: kirby.common.v1.Structure.fields:type_name -> kirby.common.v1.Field
	18, // 6: kirby.common.v1.Field.type:type_name -> kirby.common.v1.Field.Type
	12, // 7: kirby.common.v1.TreeNode.value:type_name -> kirby.common.v1.Field
	13, // 8: kirby.common.v1.TreeNode.children:type_name -> kirby.common.v1.TreeNode
	1,  // 9: kirby.common.v1.Snapshot.status:type_name -> kirby.common.v1.Snapshot.Status
	2,  // 10: kirby.common.v1.Snapshot.tags:type_name -> kirby.common.v1.Snapshot.Tag
	1,  // 11: kirby.common.v1.SimpleSnapshot.status:type_name -> kirby.common.v1.Snapshot.Status
	2,  // 12: kirby.common.v1.SimpleSnapshot.tags:type_name -> kirby.common.v1.Snapshot.Tag
	0,  // 13: kirby.common.v1.Field.Type.base_type:type_name -> kirby.common.v1.Field.BaseType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_common_entity_proto_init() }
func file_common_entity_proto_init() {
	if File_common_entity_proto != nil {
		return
	}
	file_common_annotation_proto_init()
	file_common_types_proto_init()
	file_common_entity_proto_msgTypes[13].OneofWrappers = []any{}
	file_common_entity_proto_msgTypes[15].OneofWrappers = []any{
		(*Field_Type_BaseType)(nil),
		(*Field_Type_StructureKey)(nil),
		(*Field_Type_EnumKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_entity_proto_rawDesc), len(file_common_entity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_entity_proto_goTypes,
		DependencyIndexes: file_common_entity_proto_depIdxs,
		EnumInfos:         file_common_entity_proto_enumTypes,
		MessageInfos:      file_common_entity_proto_msgTypes,
	}.Build()
	File_common_entity_proto = out.File
	file_common_entity_proto_goTypes = nil
	file_common_entity_proto_depIdxs = nil
}
